import {
  ASTNode, Program, NodeDeclaration, DefDeclaration, CmdDeclaration,
  EventDeclaration, RootDeclaration, UseStatement, ImportStatement,
  AssignStatement, LetStatement, ReturnStatement, IfStatement,
  ForInStatement, ForRangeStatement, WhileStatement, BreakStatement, ContinueStatement,
  IsExpression, EphemeralReply, CtxReply,
  AccessStatement, CooldownStatement, WaitStatement, ReactStatement, TryCatch, DmStatement,
  RoleStatement, ReplyWithButton, ButtonDeclaration, FieldDeclaration,
  OptionDeclaration, CallExpression, MemberExpression, IndexExpression,
  BinaryExpression, NullCoalesce, Identifier, Literal, ArrayLiteral,
  MapLiteral, EmbedLiteral, ParamDeclaration,
} from "./parser";
import * as fs from "fs";
import * as path from "path";
import { Lexer } from "./lexer";
import { Parser } from "./parser";

export class Transpiler {
  private output: string[] = [];
  private indentLevel = 0;
  private nodes: Map<string, NodeDeclaration> = new Map();
  private embedNodes: Set<string> = new Set();
  private buttonNodes: Set<string> = new Set();
  private modalNodes: Set<string> = new Set();
  private selectNodes: Set<string> = new Set();
  private currentFile: string = "";

  transpile(program: Program, filePath: string = ""): string {
    this.output = [];
    this.indentLevel = 0;
    this.currentFile = filePath;

    this.emit(`// Generated by NizumoScript v0.0.14`);
    this.emit(`const { Client, GatewayIntentBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder, StringSelectMenuOptionBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, REST, Routes, SlashCommandBuilder, PermissionsBitField } = require('discord.js');`);
    this.emit(`const dotenv = require('dotenv');`);
    this.emit(`const fs = require('fs');`);
    this.emit(`const path = require('path');`);
    this.emit(`dotenv.config();`);
    this.emit(``);
    this.emit(`const __client = new Client({`);
    this.emit(`  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessageReactions]`);
    this.emit(`});`);
    this.emit(`const __cooldowns = new Map();`);
    this.emit(`const __slashCommands = [];`);
    this.emit(`const __buttonHandlers = new Map();`);
    this.emit(`const __selectHandlers = new Map();`);
    this.emit(`const __modalHandlers = new Map();`);
    this.emit(``);

    this.emitStdlib();

    // Pass 1: pre-scan ALL nodes (imports + local) to populate type sets
    for (const node of program.body) {
      if (node.type === "ImportStatement") this.preScanImport(node as ImportStatement);
      if (node.type === "NodeDeclaration") {
        const n = node as NodeDeclaration;
        this.nodes.set(n.name, n);
        if (n.isEmbed) this.embedNodes.add(n.name);
        if (n.isButton) this.buttonNodes.add(n.name);
        if (n.isModal) this.modalNodes.add(n.name);
        if (n.isSelect) this.selectNodes.add(n.name);
      }
    }

    // Pass 2: emit code — imports, then local nodes, then root
    for (const node of program.body) {
      if (node.type === "ImportStatement") this.transpileImport(node as ImportStatement);
    }
    for (const node of program.body) {
      if (node.type === "NodeDeclaration") this.transpileNode(node as NodeDeclaration);
    }
    for (const node of program.body) {
      if (node.type === "RootDeclaration") this.transpileRoot(node as RootDeclaration);
    }

    return this.output.join("\n");
  }

  private transpileImport(imp: ImportStatement): void {
    const dir = this.currentFile ? path.dirname(this.currentFile) : process.cwd();
    const absPath = path.resolve(dir, imp.path);
    if (!fs.existsSync(absPath)) {
      throw new Error(`Import not found: '${imp.path}' (resolved to: ${absPath})`);
    }
    const source = fs.readFileSync(absPath, "utf-8");
    const lexer = new Lexer(source);
    const tokens = lexer.tokenize();
    const parser = new Parser(tokens, source);
    const ast = parser.parse();
    this.emit(`// ── Imported: ${imp.path} ─────────────────────────────`);
    // Only emit node declarations from imported file
    for (const node of ast.body) {
      if (node.type === "NodeDeclaration") {
        const n = node as NodeDeclaration;
        this.nodes.set(n.name, n);
        if (n.isEmbed) this.embedNodes.add(n.name);
        if (n.isButton) this.buttonNodes.add(n.name);
        if (n.isModal) this.modalNodes.add(n.name);
        if (n.isSelect) this.selectNodes.add(n.name);
        this.transpileNode(n);
      }
    }
  }

  private preScanImport(imp: ImportStatement): void {
    const dir = this.currentFile ? path.dirname(this.currentFile) : process.cwd();
    const absPath = path.resolve(dir, imp.path);
    if (!fs.existsSync(absPath)) return;
    const source = fs.readFileSync(absPath, "utf-8");
    const lexer = new Lexer(source);
    const tokens = lexer.tokenize();
    const parser = new Parser(tokens, source);
    const ast = parser.parse();
    for (const node of ast.body) {
      if (node.type === "NodeDeclaration") {
        const n = node as NodeDeclaration;
        this.nodes.set(n.name, n);
        if (n.isEmbed) this.embedNodes.add(n.name);
        if (n.isButton) this.buttonNodes.add(n.name);
        if (n.isModal) this.modalNodes.add(n.name);
        if (n.isSelect) this.selectNodes.add(n.name);
      }
    }
  }

    private emitStdlib(): void {
    this.emit(`// ── Standard Library ───────────────────────────────────`);
    // DB
    this.emit(`const __dbFile = path.resolve('.nzs_db.json');`);
    this.emit(`function __loadDb() { try { if (fs.existsSync(__dbFile)) return JSON.parse(fs.readFileSync(__dbFile,'utf8')); } catch(e){} return {}; }`);
    this.emit(`function __saveDb(d) { try { fs.writeFileSync(__dbFile, JSON.stringify(d,null,2)); } catch(e){} }`);
    this.emit(`let __dbData = __loadDb();`);
    this.emit(`const db = { get:(k)=>__dbData[k]??null, set:(k,v)=>{__dbData[k]=v;__saveDb(__dbData);return v;}, delete:(k)=>{delete __dbData[k];__saveDb(__dbData);}, has:(k)=>k in __dbData, all:()=>({...__dbData}), increment:(k,a=1)=>__dbIncrement(k,a), decrement:(k,a=1)=>__dbDecrement(k,a), keys:()=>__dbKeys(), values:()=>__dbValues() };`);
    this.emit(``);
    // reply
    this.emit(`async function __reply(ctx, message, components) {`);
    this.emit(`  if (!ctx) return;`);
    this.emit(`  const isEmbed = typeof message === 'object' && message?.data;`);
    this.emit(`  const payload = isEmbed ? { embeds: [message], components: components || [] } : { content: String(message), components: components || [] };`);
    this.emit(`  if (ctx._isSlash && ctx._interaction) {`);
    this.emit(`    if (!ctx._interaction.replied && !ctx._interaction.deferred) await ctx._interaction.reply(payload);`);
    this.emit(`    else await ctx._interaction.followUp(payload);`);
    this.emit(`  } else if (ctx.channel) { await ctx.channel.send(payload); }`);
    this.emit(`}`);
    this.emit(``);
    // dm
    this.emit(`async function __dm(target, message) {`);
    this.emit(`  try {`);
    this.emit(`    const user = target?.user || target;`);
    this.emit(`    if (!user?.send) return;`);
    this.emit(`    if (typeof message === 'object' && message?.data) await user.send({ embeds: [message] });`);
    this.emit(`    else if (typeof message === 'object' && message?.build) await user.send({ embeds: [message.build()] });`);
    this.emit(`    else await user.send(String(message));`);
    this.emit(`  } catch(e) { console.error('[NZS] DM failed:', e.message); }`);
    this.emit(`}`);
    this.emit(``);
    // send
    this.emit(`async function __send(channel, message) {`);
    this.emit(`  if (!channel) return;`);
    this.emit(`  if (typeof message === 'object' && message?.data) await channel.send({ embeds: [message] });`);
    this.emit(`  else await channel.send(String(message));`);
    this.emit(`}`);
    this.emit(``);
    // react
    this.emit(`async function __react(ctx, emoji) {`);
    this.emit(`  try {`);
    this.emit(`    if (ctx?.message?.react) await ctx.message.react(emoji);`);
    this.emit(`    else if (ctx?.channel) { const msgs = await ctx.channel.messages.fetch({ limit: 1 }); await msgs.first()?.react(emoji); }`);
    this.emit(`  } catch(e) { console.error('[NZS] React failed:', e.message); }`);
    this.emit(`}`);
    this.emit(``);
    // log
    this.emit(`function __log(...args) { const t = new Date().toLocaleTimeString('en-US',{hour12:false}); console.log(\`[NZS | \${t} | INFO]\`, ...args); }`);
    this.emit(``);
    // embed
    this.emit(`function __buildEmbed(options, fields) {`);
    this.emit(`  const e = new EmbedBuilder();`);
    this.emit(`  if (options.title) e.setTitle(String(options.title));`);
    this.emit(`  if (options.description) e.setDescription(String(options.description));`);
    this.emit(`  if (options.color) e.setColor(options.color);`);
    this.emit(`  if (options.footer) e.setFooter({ text: String(options.footer) });`);
    this.emit(`  if (options.image) e.setImage(options.image);`);
    this.emit(`  if (options.thumbnail) e.setThumbnail(options.thumbnail);`);
    this.emit(`  if (options.author) e.setAuthor({ name: String(options.author) });`);
    this.emit(`  if (options.timestamp) e.setTimestamp();`);
    this.emit(`  if (fields?.length) e.addFields(fields.map(f => ({ name: String(f.name), value: String(f.value), inline: !!f.inline })));`);
    this.emit(`  return e;`);
    this.emit(`}`);
    this.emit(``);
    // button
    this.emit(`function __buildButton(label, color, customId, handler) {`);
    this.emit(`  const styleMap = { primary: ButtonStyle.Primary, secondary: ButtonStyle.Secondary, success: ButtonStyle.Success, danger: ButtonStyle.Danger, link: ButtonStyle.Link };`);
    this.emit(`  const style = styleMap[color?.toLowerCase()] ?? ButtonStyle.Primary;`);
    this.emit(`  const btn = new ButtonBuilder().setCustomId(customId).setLabel(String(label)).setStyle(style);`);
    this.emit(`  if (handler) __buttonHandlers.set(customId, handler);`);
    this.emit(`  return new ActionRowBuilder().addComponents(btn);`);
    this.emit(`}`);
    this.emit(``);
    // select menu
    this.emit(`function __buildSelect(customId, placeholder, options, handler) {`);
    this.emit(`  const menu = new StringSelectMenuBuilder().setCustomId(customId).setPlaceholder(placeholder || 'Select an option');`);
    this.emit(`  for (const opt of options) {`);
    this.emit(`    const o = new StringSelectMenuOptionBuilder().setLabel(String(opt.label)).setValue(String(opt.value));`);
    this.emit(`    if (opt.description) o.setDescription(String(opt.description));`);
    this.emit(`    menu.addOptions(o);`);
    this.emit(`  }`);
    this.emit(`  if (handler) __selectHandlers.set(customId, handler);`);
    this.emit(`  return new ActionRowBuilder().addComponents(menu);`);
    this.emit(`}`);
    this.emit(``);
    // modal
    this.emit(`function __buildModal(customId, title, inputs) {`);
    this.emit(`  const modal = new ModalBuilder().setCustomId(customId).setTitle(title);`);
    this.emit(`  const rows = inputs.map(inp => {`);
    this.emit(`    const ti = new TextInputBuilder().setCustomId(inp.customId || inp.label).setLabel(String(inp.label)).setStyle(inp.paragraph ? TextInputStyle.Paragraph : TextInputStyle.Short).setRequired(!!inp.required);`);
    this.emit(`    if (inp.placeholder) ti.setPlaceholder(inp.placeholder);`);
    this.emit(`    return new ActionRowBuilder().addComponents(ti);`);
    this.emit(`  });`);
    this.emit(`  modal.addComponents(...rows);`);
    this.emit(`  return modal;`);
    this.emit(`}`);
    this.emit(``);
    // role
    this.emit(`async function __roleGive(member, roleName) { if (!member?.guild) return; const role = member.guild.roles.cache.find(r=>r.name===roleName)||member.guild.roles.cache.get(roleName); if (role) await member.roles.add(role).catch(e=>console.error('[NZS] Role give failed:',e.message)); }`);
    this.emit(`async function __roleRemove(member, roleName) { if (!member?.guild) return; const role = member.guild.roles.cache.find(r=>r.name===roleName)||member.guild.roles.cache.get(roleName); if (role) await member.roles.remove(role).catch(e=>console.error('[NZS] Role remove failed:',e.message)); }`);
    this.emit(``);
    // utils
    this.emit(`function __random(min,max){return Math.floor(Math.random()*(max-min+1))+min;}`);
    this.emit(`async function __fetch(url){const r=await fetch(url);return r.json();}`);
    this.emit(`function __format(v){return typeof v==='number'?v.toLocaleString():String(v);}`);
    this.emit(`function __parseDuration(str){if(typeof str==='number')return str;const n=parseInt(str);if(str.endsWith('s'))return n*1000;if(str.endsWith('m'))return n*60000;if(str.endsWith('h'))return n*3600000;return n;}`);
    this.emit(`function __wait(d){return new Promise(r=>setTimeout(r,__parseDuration(d)));}`);
    this.emit(`function __checkPermission(member,level){if(!member)return level==='@everyone';if(level==='@everyone')return true;if(level==='@admin')return member.permissions.has(PermissionsBitField.Flags.Administrator);if(level==='@mod')return member.permissions.has(PermissionsBitField.Flags.ModerateMembers);return false;}`);
    this.emit(`function __checkCooldown(cmd,userId,duration){const key=\`\${cmd}:\${userId}\`;const now=Date.now();const ms=__parseDuration(duration);if(__cooldowns.has(key)){const exp=__cooldowns.get(key);if(now<exp)return exp-now;}__cooldowns.set(key,now+ms);return 0;}`);
    this.emit(`function __interpolate(str,vars){return str.replace(/\\{([^}]+)\\}/g,(_,key)=>{const keys=key.split('.');let val=vars;for(const k of keys)val=val?.[k];return val!==undefined&&val!==null?String(val):\`{\${key}}\`;});}`);
    this.emit(``);
    // string methods
    this.emit(`const __str = { upper:(s)=>String(s).toUpperCase(), lower:(s)=>String(s).toLowerCase(), trim:(s)=>String(s).trim(), length:(s)=>String(s).length, includes:(s,v)=>String(s).includes(v), replace:(s,a,b)=>String(s).replace(a,b), split:(s,d)=>String(s).split(d), startsWith:(s,v)=>String(s).startsWith(v), endsWith:(s,v)=>String(s).endsWith(v), slice:(s,a,b)=>String(s).slice(a,b), indexOf:(s,v)=>String(s).indexOf(v) };`);
    this.emit(``);
    // math
    this.emit(`const __math = { floor:Math.floor, ceil:Math.ceil, round:Math.round, abs:Math.abs, max:Math.max, min:Math.min, pow:Math.pow, sqrt:Math.sqrt, random:Math.random, PI:Math.PI };`);
    this.emit(`function __number(v){const n=Number(v);return isNaN(n)?0:n;}`);
    this.emit(`function __string(v){return String(v);}`);
    this.emit(`function __boolean(v){return Boolean(v);}`);
    this.emit(``);
    // ctx.reply (ping reply)
    this.emit(`async function __ctxReply(ctx, message) {`);
    this.emit(`  if (!ctx) return;`);
    this.emit(`  const isEmbed = typeof message === 'object' && message?.data;`);
    this.emit(`  const payload = isEmbed ? { embeds: [message] } : { content: String(message) };`);
    this.emit(`  if (ctx._isSlash && ctx._interaction) {`);
    this.emit(`    if (!ctx._interaction.replied) await ctx._interaction.reply({ ...payload, ephemeral: false });`);
    this.emit(`    else await ctx._interaction.followUp(payload);`);
    this.emit(`  } else if (ctx.message?.reply) {`);
    this.emit(`    await ctx.message.reply(payload);`);
    this.emit(`  } else if (ctx.channel) {`);
    this.emit(`    await ctx.channel.send(payload);`);
    this.emit(`  }`);
    this.emit(`}`);
    this.emit(``);
    // ephemeral reply
    this.emit(`async function __replyEphemeral(ctx, message) {`);
    this.emit(`  if (!ctx) return;`);
    this.emit(`  const isEmbed = typeof message === 'object' && message?.data;`);
    this.emit(`  const payload = isEmbed ? { embeds: [message], ephemeral: true } : { content: String(message), ephemeral: true };`);
    this.emit(`  if (ctx._isSlash && ctx._interaction) {`);
    this.emit(`    if (!ctx._interaction.replied) await ctx._interaction.reply(payload);`);
    this.emit(`    else await ctx._interaction.followUp(payload);`);
    this.emit(`  } else if (ctx.channel) {`);
    this.emit(`    await ctx.channel.send(String(message)); // prefix cmds can't be ephemeral`);
    this.emit(`  }`);
    this.emit(`}`);
    this.emit(``);
    // attach file
    this.emit(`async function __attach(ctx, filePath, message) {`);
    this.emit(`  if (!ctx) return;`);
    this.emit(`  const payload = { files: [filePath] };`);
    this.emit(`  if (message) payload.content = String(message);`);
    this.emit(`  if (ctx._isSlash && ctx._interaction) {`);
    this.emit(`    if (!ctx._interaction.replied) await ctx._interaction.reply(payload);`);
    this.emit(`    else await ctx._interaction.followUp(payload);`);
    this.emit(`  } else if (ctx.channel) { await ctx.channel.send(payload); }`);
    this.emit(`}`);
    this.emit(``);
    // channel send by name or ID
    this.emit(`async function __channelSend(guild, channelRef, message) {`);
    this.emit(`  if (!guild) return;`);
    this.emit(`  const ch = guild.channels.cache.find(c => c.name === channelRef || c.id === channelRef);`);
    this.emit(`  if (!ch) { console.error('[NZS] Channel not found:', channelRef); return; }`);
    this.emit(`  if (typeof message === 'object' && message?.data) await ch.send({ embeds: [message] });`);
    this.emit(`  else await ch.send(String(message));`);
    this.emit(`}`);
    this.emit(``);
    // db extras
    this.emit(`function __dbIncrement(key, amount=1) { const v = Number(__dbData[key]??0)+Number(amount); __dbData[key]=v; __saveDb(__dbData); return v; }`);
    this.emit(`function __dbDecrement(key, amount=1) { const v = Number(__dbData[key]??0)-Number(amount); __dbData[key]=v; __saveDb(__dbData); return v; }`);
    this.emit(`function __dbKeys() { return Object.keys(__dbData); }`);
    this.emit(`function __dbValues() { return Object.values(__dbData); }`);
    this.emit(``);
    // server info helper
    this.emit(`function __serverInfo(guild) {`);
    this.emit(`  if (!guild) return { name: 'Unknown', id: '0', memberCount: 0, icon: null };`);
    this.emit(`  return { name: guild.name, id: guild.id, memberCount: guild.memberCount, icon: guild.iconURL() };`);
    this.emit(`}`);
    this.emit(``);
    // mentioned user helper
    this.emit(`function __getMentioned(message) {`);
    this.emit(`  if (!message) return null;`);
    this.emit(`  return message.mentions?.users?.first() || null;`);
    this.emit(`}`);
    this.emit(``);
  }

  private transpileNode(node: NodeDeclaration): void {
    this.emit(`// Node: ${node.name}${node.isEmbed?" [Embed]":node.isButton?" [Button]":node.isModal?" [Modal]":node.isSelect?" [Select]":""}`);
    this.emit(`const ${node.name} = (() => {`);
    this.indent();

    const props = node.body.filter(s => s.type === "AssignStatement") as AssignStatement[];
    const methods = node.body.filter(s => s.type === "DefDeclaration") as DefDeclaration[];
    const fields = node.body.filter(s => s.type === "FieldDeclaration") as FieldDeclaration[];
    const options = node.body.filter(s => s.type === "OptionDeclaration") as OptionDeclaration[];
    const inputFields = fields.filter(f => (f as any)._isInput);
    const embedFields = fields.filter(f => !(f as any)._isInput);

    this.emit(`const __state = {`);
    this.indent();
    for (const p of props) this.emit(`${p.name}: ${this.exprRaw(p.value)},`);
    this.dedent();
    this.emit(`};`);
    this.emit(`const __fields = [${embedFields.map(f=>`{name:${this.exprRaw(f.name)},value:${this.exprRaw(f.value)},inline:${f.inline}}`).join(",")}];`);
    this.emit(`const __options = [${options.map(o=>`{label:${this.exprRaw(o.label)},value:${this.exprRaw(o.value)}${o.description?`,description:${this.exprRaw(o.description)}`:``}}`).join(",")}];`);
    this.emit(`const __inputs = [${inputFields.map(f=>`{label:${this.exprRaw(f.name)},placeholder:${this.exprRaw(f.value)},required:${f.inline}}`).join(",")}];`);
    this.emit(``);

    if (node.isEmbed) {
      this.emit(`function build(overrides={},extraFields=[]){return __buildEmbed({...__state,...overrides},[...__fields,...extraFields]);}`);
      // addField method — allows dynamic field adding
      this.emit(`function addField(name,value,inline=false){return __buildEmbed(__state,[...__fields,{name,value,inline}]);}`);
      this.emit(``);
    }

    if (node.isButton) {
      const onClick = methods.find(m => m.name === "onClick");
      if (onClick) {
        this.emit(`const __customId = __state.customId || '${node.name.toLowerCase()}_btn';`);
        this.emit(`__buttonHandlers.set(__customId, async (ctx) => {`);
        this.indent();
        this.emit(`const __vars = { ctx };`);
        for (const s of onClick.body) this.emit(this.stmt(s, "node", "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildButton(__state.label,__state.color,__state.customId||'${node.name.toLowerCase()}_btn',null);}`);
      this.emit(``);
    }

    if (node.isModal) {
      const onSubmit = methods.find(m => m.name === "onSubmit");
      this.emit(`const __modalId = __state.customId || '${node.name.toLowerCase()}_modal';`);
      if (onSubmit) {
        this.emit(`__modalHandlers.set(__modalId, async (ctx, fields) => {`);
        this.indent();
        this.emit(`const __vars = { ctx, fields };`);
        for (const s of onSubmit.body) this.emit(this.stmt(s, "node", "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildModal(__modalId, String(__state.title||'${node.name}'), __inputs);}`);
      this.emit(``);
    }

    if (node.isSelect) {
      const onSelect = methods.find(m => m.name === "onSelect");
      this.emit(`const __selectId = __state.customId || '${node.name.toLowerCase()}_select';`);
      if (onSelect) {
        this.emit(`__selectHandlers.set(__selectId, async (ctx, values) => {`);
        this.indent();
        this.emit(`const __vars = { ctx, values, selected: values[0] };`);
        for (const s of onSelect.body) this.emit(this.stmt(s, "node", "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildSelect(__selectId, String(__state.placeholder||'Select an option'), __options, null);}`);
      this.emit(``);
    }

    this.emit(`async function onLoad(){}`);
    this.emit(`async function onUnload(){}`);
    this.emit(``);

    const skipMethods = new Set(["onLoad","onUnload","onClick","onSubmit","onSelect"]);
    for (const method of methods) {
      if (skipMethods.has(method.name)) continue;
      this.emit(`async function ${method.name}(${method.params.join(", ")}) {`);
      this.indent();
      const paramVars = method.params.length > 0 ? `{ ${method.params.join(", ")} }` : "{}";
      this.emit(`const __vars = ${paramVars};`);
      for (const s of method.body) this.emit(this.stmt(s, node.name, "__vars", null));
      this.dedent();
      this.emit(`}`);
      this.emit(``);
    }

    const exportedMethods = methods.filter(m => !m.isPrivate && !skipMethods.has(m.name)).map(m => m.name);
    const extras = [node.isEmbed||node.isButton||node.isModal||node.isSelect ? "build" : "", node.isEmbed ? "addField" : ""].filter(Boolean);
    this.emit(`return { __state, __fields, __options, __inputs, onLoad, onUnload, ${[...extras,...exportedMethods].join(", ")} };`);
    this.dedent();
    this.emit(`})();`);
    this.emit(``);
  }

  private transpileRoot(root: RootDeclaration): void {
    this.emit(`// ── Root ────────────────────────────────────────────────`);
    this.emit(`(async () => {`);
    this.indent();

    const usedNodes: string[] = [];
    const commands: CmdDeclaration[] = [];
    const events: EventDeclaration[] = [];
    const assigns: AssignStatement[] = [];

    for (const item of root.body) {
      if (item.type === "UseStatement") usedNodes.push((item as UseStatement).name);
      else if (item.type === "CmdDeclaration") commands.push(item as CmdDeclaration);
      else if (item.type === "EventDeclaration") events.push(item as EventDeclaration);
      else if (item.type === "AssignStatement") assigns.push(item as AssignStatement);
    }

    let token = `process.env.TOKEN`, clientId = `process.env.CLIENT_ID`;
    let globalPrefixes: string[] = ["!"];
    for (const a of assigns) {
      if (a.name === "token") token = this.exprRaw(a.value);
      if (a.name === "clientId") clientId = this.exprRaw(a.value);
      if (a.name === "prefix") {
        if (a.value.type === "ArrayLiteral") {
          globalPrefixes = (a.value as ArrayLiteral).elements.map(e => (e as Literal).value as string);
        } else if (a.value.type === "Literal") {
          globalPrefixes = [(a.value as Literal).value as string];
        }
      }
    }
    this.emit(`const __prefixes = ${JSON.stringify(globalPrefixes)};`);
    this.emit(`const __token = ${token};`);
    this.emit(`const __clientId = ${clientId};`);
    this.emit(``);

    for (const name of usedNodes) this.emit(`await ${name}.onLoad();`);
    this.emit(``);

    const slashCmds = commands.filter(c => c.isSlash);
    for (const cmd of slashCmds) {
      this.emit(`__slashCommands.push(new SlashCommandBuilder().setName('${cmd.name.toLowerCase()}').setDescription('${cmd.name} command')${
        cmd.params.map((p: ParamDeclaration) => `.addStringOption(o=>o.setName('${p.name}').setDescription('${p.name}').setRequired(false))`).join("")
      }.toJSON());`);
    }
    this.emit(``);

    // Ready
    this.emit(`__client.once('clientReady', async (c) => {`);
    this.indent();
    this.emit(`const ctx = null; const __vars = { client: c };`);
    if (slashCmds.length > 0) {
      this.emit(`try {`);
      this.emit(`  const rest = new REST({ version: '10' }).setToken(__token);`);
      this.emit(`  await rest.put(Routes.applicationCommands(__clientId), { body: __slashCommands });`);
      this.emit(`  __log('Slash commands registered.');`);
      this.emit(`} catch(e) { console.error('[NZS] Slash registration failed:', e.message); }`);
    }
    for (const ev of events.filter(e => e.event === "ready")) {
      for (const s of ev.body) this.emit(this.stmt(s, "root", "__vars", "null"));
    }
    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // Interactions (slash + button + select + modal)
    this.emit(`__client.on('interactionCreate', async (interaction) => {`);
    this.indent();

    // Slash
    this.emit(`if (interaction.isChatInputCommand()) {`);
    this.indent();
    this.emit(`const ctx = { user: interaction.user, channel: interaction.channel, server: interaction.guild, member: interaction.member, _isSlash: true, _interaction: interaction, args: [] };`);
    for (const cmd of slashCmds) {
      this.emit(`if (interaction.commandName === '${cmd.name.toLowerCase()}') {`);
      this.indent();
      for (const p of cmd.params) this.emit(`const ${(p as ParamDeclaration).name} = interaction.options.getString('${(p as ParamDeclaration).name}') || null;`);
      this.emitCmdBody(cmd, "ctx");
      this.dedent();
      this.emit(`}`);
    }
    this.dedent();
    this.emit(`}`);

    // Buttons
    this.emit(`if (interaction.isButton()) {`);
    this.indent();
    this.emit(`const handler = __buttonHandlers.get(interaction.customId);`);
    this.emit(`if (handler) {`);
    this.indent();
    this.emit(`const ctx = { user: interaction.user, channel: interaction.channel, server: interaction.guild, member: interaction.member, _isSlash: true, _interaction: interaction, args: [] };`);
    this.emit(`try { await handler(ctx); } catch(e) { console.error('[NZS] Button error:', e.message); if (!interaction.replied) await interaction.reply({ content: 'An error occurred.', ephemeral: true }); }`);
    this.dedent();
    this.emit(`}`);
    this.dedent();
    this.emit(`}`);

    // Select menus
    this.emit(`if (interaction.isStringSelectMenu()) {`);
    this.indent();
    this.emit(`const handler = __selectHandlers.get(interaction.customId);`);
    this.emit(`if (handler) {`);
    this.indent();
    this.emit(`const ctx = { user: interaction.user, channel: interaction.channel, server: interaction.guild, member: interaction.member, _isSlash: true, _interaction: interaction, args: [] };`);
    this.emit(`try { await handler(ctx, interaction.values); } catch(e) { console.error('[NZS] Select error:', e.message); if (!interaction.replied) await interaction.reply({ content: 'An error occurred.', ephemeral: true }); }`);
    this.dedent();
    this.emit(`}`);
    this.dedent();
    this.emit(`}`);

    // Modals
    this.emit(`if (interaction.isModalSubmit()) {`);
    this.indent();
    this.emit(`const handler = __modalHandlers.get(interaction.customId);`);
    this.emit(`if (handler) {`);
    this.indent();
    this.emit(`const ctx = { user: interaction.user, channel: interaction.channel, server: interaction.guild, member: interaction.member, _isSlash: true, _interaction: interaction, args: [] };`);
    this.emit(`const fields = { get: (id) => interaction.fields.getTextInputValue(id) };`);
    this.emit(`try { await handler(ctx, fields); } catch(e) { console.error('[NZS] Modal error:', e.message); if (!interaction.replied) await interaction.reply({ content: 'An error occurred.', ephemeral: true }); }`);
    this.dedent();
    this.emit(`}`);
    this.dedent();
    this.emit(`}`);

    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // Message / prefix commands
    const prefixCmds = commands.filter(c => !c.isSlash);
    const messageEvents = events.filter(e => e.event === "message");

    this.emit(`__client.on('messageCreate', async (message) => {`);
    this.indent();
    this.emit(`if (message.author.bot) return;`);
    this.emit(`const ctx = { user: message.author, channel: message.channel, server: message.guild, member: message.member, message, args: [], _isSlash: false, get mentioned() { return __getMentioned(message); } };`);
    this.emit(`const __vars = { message, ctx, user: message.author };`);

    for (const ev of messageEvents) {
      this.emit(`try {`);
      this.indent();
      for (const s of ev.body) this.emit(this.stmt(s, "root", "__vars", "ctx"));
      this.dedent();
      this.emit(`} catch(e) { console.error('[NZS] on message error:', e.message); }`);
    }

    if (prefixCmds.length > 0) {
      // Custom prefix commands — checked independently, outside global prefix block
      const customPrefixCmds = prefixCmds.filter(c => c.cmdPrefix);
      const globalPrefixCmds = prefixCmds.filter(c => !c.cmdPrefix);

      for (const cmd of customPrefixCmds) {
        const cmdNames = [cmd.name.toLowerCase(), ...(cmd.aliases || []).map((a: string) => a.toLowerCase())];
        const cmdPrefixes = Array.isArray(cmd.cmdPrefix) ? cmd.cmdPrefix : [cmd.cmdPrefix as string];
        const prefixCheck = cmdPrefixes.map(p => `message.content.startsWith('${p}')`).join(" || ");
        const cmdPrefixVar = `__cmdPrefix_${cmd.name}`;
        this.emit(`// cmd ${cmd.name} — custom prefix: ${cmdPrefixes.join(", ")}`);
        this.emit(`if (${prefixCheck}) {`);
        this.indent();
        this.emit(`const ${cmdPrefixVar} = [${cmdPrefixes.map(p=>`'${p}'`).join(",")}].find(p=>message.content.startsWith(p));`);
        this.emit(`const __cmdArgs_${cmd.name} = message.content.slice(${cmdPrefixVar}.length).trim().split(/ +/);`);
        this.emit(`const __cmdName_${cmd.name} = (__cmdArgs_${cmd.name}.shift() || '').toLowerCase();`);
        this.emit(`if (${cmdNames.map(n=>`__cmdName_${cmd.name} === '${n}'`).join(" || ")}) {`);
        this.indent();
        this.emit(`ctx.args = __cmdArgs_${cmd.name};`);
        this.emit(`ctx.prefix = ${cmdPrefixVar};`);
        for (let i = 0; i < cmd.params.length; i++) {
          this.emit(`const ${(cmd.params[i] as ParamDeclaration).name} = __cmdArgs_${cmd.name}[${i}] || null;`);
        }
        this.emitCmdBody(cmd, "ctx");
        this.dedent();
        this.emit(`}`);
        this.dedent();
        this.emit(`}`);
        this.emit(``);
      }

      // Global prefix commands
      if (globalPrefixCmds.length > 0) {
        this.emit(`const __matchedPrefix = __prefixes.find(p => message.content.startsWith(p));`);
        this.emit(`if (__matchedPrefix) {`);
        this.indent();
        this.emit(`const args = message.content.slice(__matchedPrefix.length).trim().split(/ +/);`);
        this.emit(`const cmdName = (args.shift() || '').toLowerCase();`);
        this.emit(`ctx.args = args;`);
        this.emit(`ctx.prefix = __matchedPrefix;`);
        for (const cmd of globalPrefixCmds) {
          const cmdNames = [cmd.name.toLowerCase(), ...(cmd.aliases || []).map((a: string) => a.toLowerCase())];
          const nameCheck = cmdNames.map(n => `cmdName === '${n}'`).join(" || ");
          this.emit(`if (${nameCheck}) {`);
          this.indent();
          for (let i = 0; i < cmd.params.length; i++) {
            this.emit(`const ${(cmd.params[i] as ParamDeclaration).name} = args[${i}] || null;`);
          }
          this.emitCmdBody(cmd, "ctx");
          this.dedent();
          this.emit(`}`);
        }
        this.dedent();
        this.emit(`}`);
      }
    }
    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // Other events
    const eventMap: Record<string, string> = {
      join: "guildMemberAdd", leave: "guildMemberRemove",
      reaction: "messageReactionAdd", ban: "guildBanAdd", unban: "guildBanRemove",
      error: "error", voiceJoin: "voiceStateUpdate", voiceLeave: "voiceStateUpdate",
    };
    for (const ev of events.filter(e => e.event !== "message" && e.event !== "ready")) {
      const de = eventMap[ev.event] || ev.event;
      this.emit(`__client.on('${de}', async (__arg) => {`);
      this.indent();
      this.emit(`try {`);
      this.indent();
      this.emit(`const user = __arg.user || __arg.member?.user || __arg;`);
      this.emit(`const ctx = { user, server: __arg.guild, member: __arg.member || __arg, message: __arg.message || null, _isSlash: false };`);
      this.emit(`const __vars = { user, ctx };`);
      for (const s of ev.body) this.emit(this.stmt(s, "root", "__vars", "ctx"));
      this.dedent();
      this.emit(`} catch(e) { console.error('[NZS] on ${ev.event} error:', e.message); }`);
      this.dedent();
      this.emit(`});`);
      this.emit(``);
    }

    this.emit(`await __client.login(__token);`);
    this.dedent();
    this.emit(`})();`);
  }

  private emitCmdBody(cmd: CmdDeclaration, ctxVar: string): void {
    let accessLevel = "@everyone", cooldownDuration: string | null = null;
    for (const s of cmd.body) {
      if (s.type === "AccessStatement") accessLevel = (s as AccessStatement).level;
      if (s.type === "CooldownStatement") cooldownDuration = (s as CooldownStatement).duration;
    }
    const paramNames = cmd.params.map((p: ParamDeclaration) => p.name).join(", ");
    const memberExpr = cmd.isSlash ? "interaction.member" : "message.member";

    this.emit(`if (!__checkPermission(${memberExpr}, '${accessLevel}')) {`);
    if (cmd.isSlash) this.emit(`  if (!interaction.replied) await interaction.reply({ content: 'No permission.', ephemeral: true });`);
    else this.emit(`  await message.channel.send('You do not have permission.');`);
    this.emit(`  return;`);
    this.emit(`}`);

    if (cooldownDuration) {
      const userId = cmd.isSlash ? "interaction.user.id" : "message.author.id";
      this.emit(`const __cd = __checkCooldown('${cmd.name}', ${userId}, '${cooldownDuration}');`);
      this.emit(`if (__cd > 0) {`);
      const msg = "Please wait ${Math.ceil(__cd/1000)}s before using this command again.";
      if (cmd.isSlash) this.emit(`  if (!interaction.replied) await interaction.reply({ content: \`${msg}\`, ephemeral: true });`);
      else this.emit(`  await message.channel.send(\`${msg}\`);`);
      this.emit(`  return;`);
      this.emit(`}`);
    }

    this.emit(`try {`);
    this.indent();
    this.emit(`const __vars = { ctx: ${ctxVar}, user: ${ctxVar}.user${paramNames ? ", " + paramNames : ""} };`);
    // Pre-populate __vars.vars so {vars.hp} etc work in string interpolation
    this.emit(`const __userId = ${ctxVar}?.user?.id ?? 'global';`);
    this.emit(`__vars['vars'] = Object.fromEntries(Object.keys(vars.__defaults).map(k => [k, __varsGet('vars', __userId, k, vars.__defaults[k])]));`);
    for (const s of cmd.body) {
      if (s.type === "AccessStatement" || s.type === "CooldownStatement") continue;
      this.emit(this.stmt(s, "root", "__vars", ctxVar));
    }
    this.dedent();
    this.emit(`} catch(e) {`);
    this.emit(`  console.error('[NZS] cmd ${cmd.name} error:', e.message);`);
    if (cmd.isSlash) this.emit(`  if (!interaction.replied) await interaction.reply({ content: 'An error occurred.', ephemeral: true });`);
    else this.emit(`  await message.channel.send('An error occurred.');`);
    this.emit(`}`);
  }

  private stmt(node: ASTNode, context: string, varsName: string, ctxExpr: string | null): string {
    switch (node.type) {
      case "ModeStatement": return `/* mode: ${(node as ModeStatement).mode} */`;
      case "VarStatement": {
        const v = node as VarStatement;
        const val = this.expr(v.value, varsName, ctxExpr);
        return `let ${v.name} = ${val}; ${varsName}['${v.name}'] = ${v.name};`;
      }
      case "LetStatement": {
        const l = node as LetStatement;
        const val = this.expr(l.value, varsName, ctxExpr);
        return `let ${l.name} = ${val}; ${varsName}['${l.name}'] = ${l.name};`;
      }
      case "AssignStatement": {
        const a = node as AssignStatement;
        const val = this.expr(a.value, varsName, ctxExpr);
        // vars.field = / += / -= route through db helpers, then populate __vars for interpolation
        if (a.name.startsWith("vars.")) {
          const field = a.name.slice(5);
          const userId = `${ctxExpr ?? "null"}?.user?.id ?? 'global'`;
          let line = "";
          if (a.operator === "=")  line = `__varsSet('vars', ${userId}, '${field}', ${val});`;
          else if (a.operator === "+=") line = `__varsMod('vars', ${userId}, '${field}', ${val}, vars.__defaults['${field}'] ?? 0);`;
          else if (a.operator === "-=") line = `__varsMod('vars', ${userId}, '${field}', -(${val}), vars.__defaults['${field}'] ?? 0);`;
          else line = `__varsSet('vars', ${userId}, '${field}', ${val});`;
          // also refresh __vars.vars so interpolation picks it up
          return `${line} if(!${varsName}['vars']) ${varsName}['vars']={}; ${varsName}['vars']['${field}'] = __varsGet('vars', ${userId}, '${field}', vars.__defaults['${field}']);`;
        }
        if (a.operator === "=" && a.isDeclaration) return `let ${a.name} = ${val}; ${varsName}['${a.name}'] = ${a.name};`;
        return `${a.name} ${a.operator} ${val}; ${varsName}['${a.name}'] = ${a.name};`;
      }
      case "ReturnStatement": { const r = node as ReturnStatement; return r.value ? `return ${this.expr(r.value, varsName, ctxExpr)};` : `return;`; }
      case "IfStatement": {
        const i = node as IfStatement;
        let out = `if (${this.expr(i.condition, varsName, ctxExpr)}) {\n`;
        for (const s of i.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}\n`;
        out += `}`;
        for (const ei of (i.elseIfs || [])) {
          out += ` else if (${this.expr(ei.condition, varsName, ctxExpr)}) {\n`;
          for (const s of ei.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}\n`;
          out += `}`;
        }
        if (i.elseBody) { out += ` else {\n`; for (const s of i.elseBody) out += `  ${this.stmt(s, context, varsName, ctxExpr)}\n`; out += `}`; }
        return out;
      }
      case "TryCatch": {
        const t = node as TryCatch;
        let out = `try {\n`;
        for (const s of t.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}\n`;
        out += `} catch(${t.catchVar}) {\n`;
        for (const s of t.catchBody) out += `  ${this.stmt(s, context, varsName, ctxExpr)}\n`;
        out += `}`;
        return out;
      }
      case "WaitStatement": return `await __wait('${(node as WaitStatement).duration}');`;
      case "ReactStatement": return `await __react(${ctxExpr ?? "null"}, ${this.expr((node as ReactStatement).emoji, varsName, ctxExpr)});`;
      case "EphemeralReply": return `await __replyEphemeral(${ctxExpr ?? "null"}, ${this.expr((node as EphemeralReply).message, varsName, ctxExpr)});`;
      case "CtxReply": return `await __ctxReply(${ctxExpr ?? "null"}, ${this.expr((node as CtxReply).message, varsName, ctxExpr)});`;
      case "BreakStatement": return `break;`;
      case "ContinueStatement": return `continue;`;
      case "ForInStatement": {
        const f = node as ForInStatement;
        let out = `for (const ${f.variable} of (${this.expr(f.iterable, varsName, ctxExpr)} || [])) {
`;
        out += `  ${varsName}['${f.variable}'] = ${f.variable};
`;
        for (const s of f.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}
`;
        out += `}`;
        return out;
      }
      case "ForRangeStatement": {
        const f = node as ForRangeStatement;
        const from = this.expr(f.from, varsName, ctxExpr);
        const to = this.expr(f.to, varsName, ctxExpr);
        let out = `for (let ${f.variable} = ${from}; ${f.variable} <= ${to}; ${f.variable}++) {
`;
        out += `  ${varsName}['${f.variable}'] = ${f.variable};
`;
        for (const s of f.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}
`;
        out += `}`;
        return out;
      }
      case "WhileStatement": {
        const w = node as WhileStatement;
        let out = `while (${this.expr(w.condition, varsName, ctxExpr)}) {
`;
        for (const s of w.body) out += `  ${this.stmt(s, context, varsName, ctxExpr)}
`;
        out += `}`;
        return out;
      }
      case "CooldownStatement": case "AccessStatement": return `/* handled */`;
      case "DmStatement": { const d = node as DmStatement; return `await __dm(${this.expr(d.target, varsName, ctxExpr)}, ${this.expr(d.message, varsName, ctxExpr)});`; }
      case "RoleStatement": { const r = node as RoleStatement; return `await ${r.action === "give" ? "__roleGive" : "__roleRemove"}(${this.expr(r.target, varsName, ctxExpr)}, ${this.expr(r.role, varsName, ctxExpr)});`; }
      case "ReplyWithButton": {
        const rwb = node as ReplyWithButton;
        const msg = this.expr(rwb.message, varsName, ctxExpr);
        const ctx = ctxExpr ?? "null";
        if (typeof rwb.button === "string") {
          return `await __reply(${ctx}, ${msg}, [${rwb.button}.build()]);`;
        } else {
          const btn = rwb.button as ButtonDeclaration;
          const labelExpr = this.expr(btn.label, varsName, ctxExpr);
          const cid = btn.customId;
          let out = `__buttonHandlers.set('${cid}', async (ctx) => {\n  const __vars = { ctx };\n`;
          for (const s of btn.onClickBody) out += `  ${this.stmt(s, context, "__vars", "ctx")}\n`;
          out += `});\nawait __reply(${ctx}, ${msg}, [__buildButton(${labelExpr}, '${btn.color}', '${cid}', null)]);`;
          return out;
        }
      }
      case "CallExpression": return `${this.call(node as CallExpression, varsName, ctxExpr)};`;
      default: return `/* ${node.type} */`;
    }
  }

  private expr(node: ASTNode, varsName: string = "__vars", ctxExpr: string | null = "ctx"): string {
    switch (node.type) {
      case "Literal": {
        const l = node as Literal;
        if (l.value === null) return "null";
        if (typeof l.value === "boolean") return String(l.value);
        if (typeof l.value === "string") {
          const esc = l.value.replace(/`/g, "\\`").replace(/\$/g, "\\$");
          return `__interpolate(\`${esc}\`, ${varsName} || {})`;
        }
        return String(l.value);
      }
      case "Identifier": {
        const id = node as Identifier;
        if (id.name === "env") return "process.env";
        if (id.name === "log") return "__log";
        if (id.name === "random") return "__random";
        if (id.name === "fetch") return "__fetch";
        if (id.name === "format") return "__format";
        if (id.name === "send") return "__send";
        if (id.name === "attach") return "__attach";
        if (id.name === "number") return "__number";
        if (id.name === "string") return "__string";
        if (id.name === "boolean") return "__boolean";
        if (this.embedNodes.has(id.name)) return `${id.name}.build()`;
        if (this.buttonNodes.has(id.name)) return `${id.name}.build()`;
        if (this.modalNodes.has(id.name)) return `${id.name}.build()`;
        if (this.selectNodes.has(id.name)) return `${id.name}.build()`;
        return id.name;
      }
      case "MemberExpression": {
        const m = node as MemberExpression;
        // .length on strings maps to __str.length
        if (m.property === "length" && !m.optional) {
          return `__str.length(${this.expr(m.object, varsName, ctxExpr)})`;
        }
        // ctx.mentioned -> __getMentioned(message)
        if (m.object.type === "Identifier" && (m.object as Identifier).name === "ctx" && m.property === "mentioned") {
          return `__getMentioned(${ctxExpr ?? "null"}?.message)`;
        }
        // ctx.server.name/memberCount/id/icon -> guild properties
        if (m.object.type === "MemberExpression") {
          const inner = m.object as MemberExpression;
          if (inner.object.type === "Identifier" && (inner.object as Identifier).name === "ctx" && inner.property === "server") {
            return `__serverInfo(${ctxExpr ?? "null"}?.server)?.${m.property}`;
          }
        }
        return `${this.expr(m.object, varsName, ctxExpr)}${m.optional ? "?." : "."}${m.property}`;
      }
      case "IndexExpression": {
        const ie = node as IndexExpression;
        return `${this.expr(ie.object, varsName, ctxExpr)}[${this.expr(ie.index, varsName, ctxExpr)}]`;
      }
      case "CallExpression": return this.call(node as CallExpression, varsName, ctxExpr);
      case "BinaryExpression": {
        const b = node as BinaryExpression;
        return `(${this.expr(b.left, varsName, ctxExpr)} ${b.operator} ${this.expr(b.right, varsName, ctxExpr)})`;
      }
      case "NullCoalesce": {
        const n = node as NullCoalesce;
        return `(${this.expr(n.left, varsName, ctxExpr)} ?? ${this.expr(n.right, varsName, ctxExpr)})`;
      }
      case "ArrayLiteral": return `[${(node as ArrayLiteral).elements.map(e => this.expr(e, varsName, ctxExpr)).join(", ")}]`;
      case "MapLiteral": {
        const pairs = (node as MapLiteral).pairs.map(p => `${p.key}: ${this.expr(p.value, varsName, ctxExpr)}`).join(", ");
        return `{${pairs}}`;
      }
      case "EmbedLiteral": {
        const el = node as EmbedLiteral;
        const pairs = el.pairs.map(p => `${p.key}: ${this.expr(p.value, varsName, ctxExpr)}`).join(", ");
        const fields = el.fields.map(f => `{name:${this.expr(f.name, varsName, ctxExpr)},value:${this.expr(f.value, varsName, ctxExpr)},inline:${f.inline}}`).join(", ");
        return `__buildEmbed({${pairs}},[${fields}])`;
      }
      case "IsExpression": {
        const ie = node as IsExpression;
        const val = this.expr(ie.value, varsName, ctxExpr);
        const typeMap: Record<string, string> = {
          string: `typeof ${val} === 'string'`,
          number: `typeof ${val} === 'number'`,
          boolean: `typeof ${val} === 'boolean'`,
          null: `${val} === null || ${val} === undefined`,
          array: `Array.isArray(${val})`,
        };
        const check = typeMap[ie.checkType] ?? `typeof ${val} === '${ie.checkType}'`;
        return ie.negated ? `!(${check})` : `(${check})`;
      }
      default: return "undefined";
    }
  }

  private exprRaw(node: ASTNode): string {
    switch (node.type) {
      case "Literal": {
        const l = node as Literal;
        if (l.value === null) return "null";
        if (typeof l.value === "boolean") return String(l.value);
        if (typeof l.value === "string") return `"${l.value.replace(/"/g, '\\"')}"`;
        return String(l.value);
      }
      case "Identifier": { const id = node as Identifier; return id.name === "env" ? "process.env" : id.name; }
      case "MemberExpression": { const m = node as MemberExpression; return `${this.exprRaw(m.object)}.${m.property}`; }
      default: return this.expr(node);
    }
  }

  private call(node: CallExpression, varsName: string, ctxExpr: string | null): string {
    const args = node.args.map(a => this.expr(a, varsName, ctxExpr)).join(", ");
    if (node.callee.type === "Identifier") {
      const name = (node.callee as Identifier).name;
      if (name === "reply") { const msg = node.args[0] ? this.expr(node.args[0], varsName, ctxExpr) : '""'; return `await __reply(${ctxExpr ?? "null"}, ${msg})`; }
      if (name === "log") return `__log(${args})`;
      if (name === "random") return `__random(${args})`;
      if (name === "fetch") return `await __fetch(${args})`;
      if (name === "format") return `__format(${args})`;
      if (name === "number") return `__number(${args})`;
      if (name === "string") return `__string(${args})`;
      if (name === "boolean") return `__boolean(${args})`;
      if (name === "send") return `await __send(${args})`;
      if (name === "react") return `await __react(${ctxExpr ?? "null"}, ${args})`;
      if (name === "attach") return `await __attach(${ctxExpr ?? "null"}, ${args})`;
      if (name === "channelSend") return `await __channelSend(${ctxExpr ?? "null"}?.server, ${args})`;
      if (name === "str") return `__str`;
      if (name === "math") return `__math`;
    }
    // string method shortcuts: text.upper(), text.lower(), text.includes(), etc.
    if (node.callee.type === "MemberExpression") {
      const m = node.callee as MemberExpression;
      const strMethods = ["upper","lower","trim","includes","replace","split","startsWith","endsWith","slice","indexOf"];
      const mathMethods = ["floor","ceil","round","abs","max","min","pow","sqrt"];
      if (strMethods.includes(m.property)) {
        const obj = this.expr(m.object, varsName, ctxExpr);
        if (m.property === "upper") return `__str.upper(${obj})`;
        if (m.property === "lower") return `__str.lower(${obj})`;
        if (m.property === "trim") return `__str.trim(${obj})`;
        if (m.property === "split") return `__str.split(${obj}, ${args})`;
        if (m.property === "replace") return `__str.replace(${obj}, ${args})`;
        if (m.property === "includes") return `__str.includes(${obj}, ${args})`;
        if (m.property === "startsWith") return `__str.startsWith(${obj}, ${args})`;
        if (m.property === "endsWith") return `__str.endsWith(${obj}, ${args})`;
        if (m.property === "slice") return `__str.slice(${obj}, ${args})`;
        if (m.property === "indexOf") return `__str.indexOf(${obj}, ${args})`;
      }
      if (m.object.type === "Identifier" && (m.object as Identifier).name === "math" && mathMethods.includes(m.property)) {
        return `__math.${m.property}(${args})`;
      }
    }
    // embed.addField(name, value, inline)
    if (node.callee.type === "MemberExpression") {
      const m = node.callee as MemberExpression;
      if (m.property === "addField") {
        const obj = this.expr(m.object, varsName, ctxExpr);
        return `await __reply(${ctxExpr ?? "null"}, ${obj.replace(".build()", "")}.addField(${args}))`;
      }
      if (m.property === "showModal") {
        const obj = this.expr(m.object, varsName, ctxExpr);
        return `await ${ctxExpr ?? "null"}?._interaction?.showModal(${obj.replace(".build()", "")}.build())`;
      }
      if (m.property === "edit") {
        // embed.edit(messageId) — edit an existing message
        const embedObj = this.expr(m.object, varsName, ctxExpr);
        return `await (async()=>{ try { const __msg = await ${ctxExpr ?? "null"}?.channel?.messages?.fetch(${args}); if(__msg) await __msg.edit({ embeds: [${embedObj}] }); } catch(e){ console.error('[NZS] embed.edit failed:',e.message); }})()`;
      }
    }
    return `await ${this.expr(node.callee, varsName, ctxExpr)}(${args})`;
  }

  private emit(line: string): void { this.output.push("  ".repeat(this.indentLevel) + line); }
  private indent(): void { this.indentLevel++; }
  private dedent(): void { this.indentLevel = Math.max(0, this.indentLevel - 1); }
}
