import {
  ASTNode, Program, NodeDeclaration, DefDeclaration, CmdDeclaration,
  EventDeclaration, RootDeclaration, UseStatement, ImportStatement,
  AssignStatement, LetStatement, VarStatement, ModeStatement, ReturnStatement,
  IfStatement, MatchStatement, ForInStatement, ForRangeStatement, WhileStatement,
  BreakStatement, ContinueStatement, IsExpression, EphemeralReply, CtxReply,
  AccessStatement, CooldownStatement, WaitStatement, ReactStatement, TryCatch,
  DmStatement, RoleStatement, ReplyWithButton, ButtonDeclaration, FieldDeclaration,
  OptionDeclaration, CallExpression, MemberExpression, IndexExpression,
  BinaryExpression, NullCoalesce, TernaryExpression, Identifier, Literal,
  ArrayLiteral, MapLiteral, EmbedLiteral, ParamDeclaration,
  AnimationDeclaration, SpriteDeclaration, KeyframeDeclaration, PlayStatement,
  ScheduledTask, EmitStatement, TemplateReply, PaginateStatement,
} from "./parser";
import * as fs from "fs";
import * as path from "path";
import { Lexer } from "./lexer";
import { Parser } from "./parser";

// ── Symbol Table ──────────────────────────────────────────────────────────
interface SymbolInfo {
  kind: "node" | "embed" | "button" | "modal" | "select" | "vars" | "animation" | "cmd" | "event";
  node?: NodeDeclaration;
  animNode?: AnimationDeclaration;
  parentNode?: string;
}

export class Transpiler {
  private output: string[] = [];
  private indentLevel = 0;
  private symbols: Map<string, SymbolInfo> = new Map();
  private currentFile: string = "";
  private globalMode: "beginner" | "normal" | null = null;
  private currentMode: "beginner" | "normal" | null = null;

  transpile(program: Program, filePath: string = ""): string {
    this.output = [];
    this.indentLevel = 0;
    this.currentFile = filePath;
    this.symbols = new Map();

    // Emit header
    this.emit(`// Generated by NizumoScript v0.2.0`);
    this.emit(`const { Client, GatewayIntentBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder, StringSelectMenuOptionBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, REST, Routes, SlashCommandBuilder, PermissionsBitField } = require('discord.js');`);
    this.emit(`const dotenv = require('dotenv');`);
    this.emit(`const fs = require('fs');`);
    this.emit(`const path = require('path');`);
    this.emit(`dotenv.config();`);
    this.emit(``);
    this.emit(`const __client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessageReactions] });`);
    this.emit(`const __cooldowns = new Map();`);
    this.emit(`const __slashCommands = [];`);
    this.emit(`const __buttonHandlers = new Map();`);
    this.emit(`const __selectHandlers = new Map();`);
    this.emit(`const __modalHandlers = new Map();`);
    this.emit(`const __eventHandlers = new Map();`);
    this.emit(``);

    this.emitStdlib();

    // Pass 1: scan and flatten all nodes recursively
    this.scanProgram(program.body, null);

    // Determine global mode from root
    const rootNode = program.body.find(n => n.type === "RootDeclaration") as RootDeclaration | undefined;
    if (rootNode?.mode) this.globalMode = rootNode.mode;

    // Pass 2: emit all imports
    for (const node of program.body)
      if (node.type === "ImportStatement") this.transpileImport(node as ImportStatement);

    // Pass 3: emit all node declarations (flattened)
    this.emitAllNodes(program.body);

    // Pass 4: emit root
    for (const node of program.body)
      if (node.type === "RootDeclaration") this.transpileRoot(node as RootDeclaration);

    return this.output.join("\n");
  }

  // ── Symbol scanning ───────────────────────────────────────────────────
  private scanProgram(body: ASTNode[], parentName: string | null): void {
    for (const node of body) {
      if (node.type === "NodeDeclaration") {
        const n = node as NodeDeclaration;
        const kind = this.resolveNodeKind(n);
        this.symbols.set(n.name, { kind, node: n, parentNode: parentName ?? undefined });
        // recursively scan nested nodes
        this.scanProgram(n.body, n.name);
      }
      if (node.type === "AnimationDeclaration") {
        const a = node as AnimationDeclaration;
        this.symbols.set(a.name, { kind: "animation", animNode: a });
      }
    }
  }

  private resolveNodeKind(n: NodeDeclaration): SymbolInfo["kind"] {
    const body = n.body;
    const assigns = body.filter(s => s.type === "AssignStatement") as AssignStatement[];
    const varStmts = body.filter(s => s.type === "VarStatement") as VarStatement[];
    const embedKeys = new Set(["title","description","color","footer","image","thumbnail","author","timestamp"]);
    const buttonKeys = new Set(["label","color","customId"]);
    const hasMethods = body.some(s => s.type === "DefDeclaration");
    const hasOpts = body.some(s => s.type === "OptionDeclaration");
    const hasCmds = body.some(s => s.type === "CmdDeclaration");
    const hasEvents = body.some(s => s.type === "EventDeclaration");
    const hasNestedNodes = body.some(s => s.type === "NodeDeclaration");

    // vars node: named "vars" OR only contains VarStatements
    if (n.name === "vars" || (varStmts.length > 0 && !hasCmds && !hasEvents && !hasNestedNodes && assigns.every(a => embedKeys.has(a.name) === false))) {
      const nonMode = body.filter(s => s.type !== "ModeStatement");
      if (nonMode.every(s => s.type === "VarStatement")) return "vars";
    }
    // commands node: contains cmd declarations
    if (hasCmds || hasEvents) return "node";
    // embed node: only embed-type assigns and fields
    if (assigns.length > 0 && assigns.every(a => embedKeys.has(a.name)) && !hasMethods) return "embed";
    // button node
    if (assigns.some(a => buttonKeys.has(a.name)) && body.some(s => s.type === "DefDeclaration" && (s as DefDeclaration).name === "onClick")) return "button";
    // modal node
    if (body.some(s => s.type === "FieldDeclaration" && (s as any)._isInput)) return "modal";
    // select node
    if (hasOpts) return "select";

    return "node";
  }

  // ── Emit all nodes (flattened from nested) ────────────────────────────
  private emitAllNodes(body: ASTNode[]): void {
    for (const node of body) {
      if (node.type === "NodeDeclaration") {
        const n = node as NodeDeclaration;
        const info = this.symbols.get(n.name);
        if (info?.kind === "vars") { this.transpileVarsNode(n); }
        else { this.transpileNode(n); }
        // recursively emit nested nodes
        this.emitAllNodes(n.body);
      }
      if (node.type === "AnimationDeclaration") {
        this.transpileAnimation(node as AnimationDeclaration);
      }
    }
  }

  // ── Import ────────────────────────────────────────────────────────────
  private transpileImport(imp: ImportStatement): void {
    const dir = this.currentFile ? path.dirname(this.currentFile) : process.cwd();
    const absPath = path.resolve(dir, imp.path);
    if (!fs.existsSync(absPath)) throw new Error(`[Line ${imp.line}] Import not found: '${imp.path}' — check the file path`);
    const source = fs.readFileSync(absPath, "utf-8");
    const lexer = new Lexer(source);
    const tokens = lexer.tokenize();
    const parser = new Parser(tokens, source);
    const ast = parser.parse();
    this.emit(`// ── Imported: ${imp.path} ────────────────────────`);
    this.scanProgram(ast.body, null);
    this.emitAllNodes(ast.body);
  }

  // ── Stdlib ────────────────────────────────────────────────────────────
  private emitStdlib(): void {
    this.emit(`// ── Stdlib ──────────────────────────────────────────────`);
    this.emit(`const __dbFile = path.resolve('.nzs_db.json');`);
    this.emit(`function __loadDb(){try{if(fs.existsSync(__dbFile))return JSON.parse(fs.readFileSync(__dbFile,'utf8'));}catch(e){}return {};}`);
    this.emit(`function __saveDb(d){try{fs.writeFileSync(__dbFile,JSON.stringify(d,null,2));}catch(e){}}`);
    this.emit(`let __dbData = __loadDb();`);
    this.emit(`const db={get:(k)=>__dbData[k]??null,set:(k,v)=>{__dbData[k]=v;__saveDb(__dbData);return v;},delete:(k)=>{delete __dbData[k];__saveDb(__dbData);},has:(k)=>k in __dbData,all:()=>({...__dbData}),increment:(k,a=1)=>__dbIncrement(k,a),decrement:(k,a=1)=>__dbDecrement(k,a),keys:()=>Object.keys(__dbData),values:()=>Object.values(__dbData),push:(k,v)=>{const a=Array.isArray(__dbData[k])?__dbData[k]:[];a.push(v);__dbData[k]=a;__saveDb(__dbData);return a;},pull:(k,v)=>{const a=Array.isArray(__dbData[k])?__dbData[k]:[];__dbData[k]=a.filter(x=>x!==v);__saveDb(__dbData);return __dbData[k];}};`);
    this.emit(`function __dbIncrement(k,a=1){const v=Number(__dbData[k]??0)+Number(a);__dbData[k]=v;__saveDb(__dbData);return v;}`);
    this.emit(`function __dbDecrement(k,a=1){const v=Number(__dbData[k]??0)-Number(a);__dbData[k]=v;__saveDb(__dbData);return v;}`);
    this.emit(``);
    // vars helpers
    this.emit(`function __varsGet(nodeKey,userId,field,defaultVal){const key=nodeKey+':'+userId;const obj=__dbData[key]||{};const val=obj[field];if(val===undefined)return defaultVal;try{if(typeof val==='string'&&(val.startsWith('[')||val.startsWith('{'))){return JSON.parse(val);}}catch(e){}return val;}`);
    this.emit(`function __varsSet(nodeKey,userId,field,value){const key=nodeKey+':'+userId;if(!__dbData[key])__dbData[key]={};const stored=typeof value==='object'&&value!==null?JSON.stringify(value):value;__dbData[key][field]=stored;__saveDb(__dbData);return value;}`);
    this.emit(`function __varsMod(nodeKey,userId,field,delta,defaultVal){const current=__varsGet(nodeKey,userId,field,defaultVal);return __varsSet(nodeKey,userId,field,current+delta);}`);
    this.emit(`function __varsPush(nodeKey,userId,field,value){const arr=__varsGet(nodeKey,userId,field,[])||[];arr.push(value);return __varsSet(nodeKey,userId,field,arr);}`);
    this.emit(`function __varsPull(nodeKey,userId,field,value){const arr=__varsGet(nodeKey,userId,field,[])||[];const filtered=arr.filter(x=>x!==value);return __varsSet(nodeKey,userId,field,filtered);}`);
    this.emit(``);
    // reply helpers
    this.emit(`async function __reply(ctx,message,components){if(!ctx)return;const isEmbed=typeof message==='object'&&message?.data;const payload=isEmbed?{embeds:[message],components:components||[]}:{content:String(message),components:components||[]};if(ctx._isSlash&&ctx._interaction){if(!ctx._interaction.replied&&!ctx._interaction.deferred)await ctx._interaction.reply(payload);else await ctx._interaction.followUp(payload);}else if(ctx.channel){await ctx.channel.send(payload);}}`);
    this.emit(`async function __replyEphemeral(ctx,message){if(!ctx)return;const isEmbed=typeof message==='object'&&message?.data;const payload=isEmbed?{embeds:[message],ephemeral:true}:{content:String(message),ephemeral:true};if(ctx._isSlash&&ctx._interaction){if(!ctx._interaction.replied)await ctx._interaction.reply(payload);else await ctx._interaction.followUp(payload);}else if(ctx.channel){await ctx.channel.send(String(message));}}`);
    this.emit(`async function __ctxReply(ctx,message){if(!ctx)return;const isEmbed=typeof message==='object'&&message?.data;const payload=isEmbed?{embeds:[message]}:{content:String(message)};if(ctx._isSlash&&ctx._interaction){if(!ctx._interaction.replied)await ctx._interaction.reply({...payload,ephemeral:false});else await ctx._interaction.followUp(payload);}else if(ctx.message?.reply){await ctx.message.reply(payload);}else if(ctx.channel){await ctx.channel.send(payload);}}`);
    this.emit(`async function __dm(target,message){try{const user=target?.user||target;if(!user?.send)return;if(typeof message==='object'&&message?.data)await user.send({embeds:[message]});else await user.send(String(message));}catch(e){console.error('[NZS] DM failed:',e.message);}}`);
    this.emit(`async function __send(channel,message){if(!channel)return;if(typeof message==='object'&&message?.data)await channel.send({embeds:[message]});else await channel.send(String(message));}`);
    this.emit(`async function __channelSend(guild,ref,msg){if(!guild)return;const ch=guild.channels.cache.find(c=>c.name===ref||c.id===ref);if(!ch)return;if(typeof msg==='object'&&msg?.data)await ch.send({embeds:[msg]});else await ch.send(String(msg));}`);
    this.emit(`async function __react(ctx,emoji){try{if(ctx?.message?.react)await ctx.message.react(emoji);}catch(e){}}`);
    this.emit(``);
    // build helpers
    this.emit(`function __buildEmbed(options,fields){const e=new EmbedBuilder();if(options.title)e.setTitle(String(options.title));if(options.description)e.setDescription(String(options.description));if(options.color)e.setColor(options.color);if(options.footer)e.setFooter({text:String(options.footer)});if(options.image)e.setImage(options.image);if(options.thumbnail)e.setThumbnail(options.thumbnail);if(options.author)e.setAuthor({name:String(options.author)});if(options.timestamp)e.setTimestamp();if(fields?.length)e.addFields(fields.map(f=>({name:String(f.name),value:String(f.value),inline:!!f.inline})));return e;}`);
    this.emit(`function __buildButton(label,color,customId,handler){const styleMap={primary:ButtonStyle.Primary,secondary:ButtonStyle.Secondary,success:ButtonStyle.Success,danger:ButtonStyle.Danger};const style=styleMap[color?.toLowerCase()]??ButtonStyle.Primary;const btn=new ButtonBuilder().setCustomId(customId).setLabel(String(label)).setStyle(style);if(handler)__buttonHandlers.set(customId,handler);return new ActionRowBuilder().addComponents(btn);}`);
    this.emit(`function __buildSelect(customId,placeholder,options,handler){const menu=new StringSelectMenuBuilder().setCustomId(customId).setPlaceholder(placeholder||'Select');for(const opt of options){const o=new StringSelectMenuOptionBuilder().setLabel(String(opt.label)).setValue(String(opt.value));if(opt.description)o.setDescription(String(opt.description));menu.addOptions(o);}if(handler)__selectHandlers.set(customId,handler);return new ActionRowBuilder().addComponents(menu);}`);
    this.emit(`function __buildModal(customId,title,inputs){const modal=new ModalBuilder().setCustomId(customId).setTitle(title);const rows=inputs.map(inp=>{const ti=new TextInputBuilder().setCustomId(inp.customId||inp.label).setLabel(String(inp.label)).setStyle(inp.paragraph?TextInputStyle.Paragraph:TextInputStyle.Short).setRequired(!!inp.required);if(inp.placeholder)ti.setPlaceholder(inp.placeholder);return new ActionRowBuilder().addComponents(ti);});modal.addComponents(...rows);return modal;}`);
    this.emit(``);
    // utility
    this.emit(`function __log(...args){const t=new Date().toLocaleTimeString('en-US',{hour12:false});console.log(\`[NZS | \${t}]\`,...args);}`);
    this.emit(`function __random(min,max){return Math.floor(Math.random()*(max-min+1))+min;}`);
    this.emit(`async function __fetch(url){const r=await fetch(url);return r.json();}`);
    this.emit(`function __format(v){return typeof v==='number'?v.toLocaleString():String(v);}`);
    this.emit(`function __parseDuration(str){if(typeof str==='number')return str;const n=parseInt(str);if(str.endsWith('s'))return n*1000;if(str.endsWith('m'))return n*60000;if(str.endsWith('h'))return n*3600000;if(str.endsWith('d'))return n*86400000;return n;}`);
    this.emit(`function __wait(d){return new Promise(r=>setTimeout(r,__parseDuration(d)));}`);
    this.emit(`function __checkPermission(member,level){if(!member)return level==='@everyone';if(level==='@everyone')return true;if(level==='@admin')return member.permissions.has(PermissionsBitField.Flags.Administrator);if(level==='@mod')return member.permissions.has(PermissionsBitField.Flags.ModerateMembers);return false;}`);
    this.emit(`function __checkCooldown(cmd,userId,duration){const key=\`\${cmd}:\${userId}\`;const now=Date.now();const ms=__parseDuration(duration);if(__cooldowns.has(key)){const exp=__cooldowns.get(key);if(now<exp)return exp-now;}__cooldowns.set(key,now+ms);return 0;}`);
    this.emit(`function __interpolate(str,ctx,localVars){return str.replace(/\\{([^}]+)\\}/g,(_,key)=>{if(key.startsWith('vars.')&&typeof __varsGet!=='undefined'){const field=key.slice(5);const uid=ctx?.user?.id??'global';const parts=key.split('.');const nodeKey=parts.length>2?parts[0]:('vars');const fld=parts[parts.length-1];const defNode=typeof vars!=='undefined'&&vars?.__defaults;const def=defNode?defNode[fld]:null;const v=__varsGet(nodeKey,uid,fld,def);return v!==null&&v!==undefined?String(v):'{'+key+'}';}const keys=key.split('.');let val=localVars;for(const k of keys)val=val?.[k];return val!==undefined&&val!==null?String(val):'{'+key+'}';});}`);
    this.emit(`function __number(v){const n=Number(v);return isNaN(n)?0:n;}`);
    this.emit(`function __string(v){return String(v);}`);
    this.emit(`function __boolean(v){return Boolean(v);}`);
    this.emit(`function __getMentioned(message){return message?.mentions?.users?.first()??null;}`);
    this.emit(`function __serverInfo(guild){if(!guild)return{name:'Unknown',id:'0',memberCount:0,icon:null};return{name:guild.name,id:guild.id,memberCount:guild.memberCount,icon:guild.iconURL()};}`);
    this.emit(`async function __roleGive(member,roleName){if(!member?.guild)return;const role=member.guild.roles.cache.find(r=>r.name===roleName)||member.guild.roles.cache.get(roleName);if(role)await member.roles.add(role).catch(()=>{});}`);
    this.emit(`async function __roleRemove(member,roleName){if(!member?.guild)return;const role=member.guild.roles.cache.find(r=>r.name===roleName)||member.guild.roles.cache.get(roleName);if(role)await member.roles.remove(role).catch(()=>{});}`);
    this.emit(`const __str={upper:(s)=>String(s).toUpperCase(),lower:(s)=>String(s).toLowerCase(),trim:(s)=>String(s).trim(),length:(s)=>String(s).length,includes:(s,v)=>String(s).includes(v),replace:(s,a,b)=>String(s).replace(a,b),split:(s,d)=>String(s).split(d),startsWith:(s,v)=>String(s).startsWith(v),endsWith:(s,v)=>String(s).endsWith(v),slice:(s,a,b)=>String(s).slice(a,b),indexOf:(s,v)=>String(s).indexOf(v),repeat:(s,n)=>String(s).repeat(n),reverse:(s)=>String(s).split('').reverse().join('')};`);
    this.emit(`const __math={floor:Math.floor,ceil:Math.ceil,round:Math.round,abs:Math.abs,max:Math.max,min:Math.min,pow:Math.pow,sqrt:Math.sqrt,random:Math.random,PI:Math.PI,log:Math.log,sin:Math.sin,cos:Math.cos};`);
    this.emit(`const __arr={push:(a,v)=>{if(Array.isArray(a)){a.push(v);return a;}return[v];},pop:(a)=>Array.isArray(a)?a.pop():null,length:(a)=>Array.isArray(a)?a.length:0,includes:(a,v)=>Array.isArray(a)&&a.includes(v),filter:(a,fn)=>Array.isArray(a)?a.filter(fn):[],map:(a,fn)=>Array.isArray(a)?a.map(fn):[],find:(a,fn)=>Array.isArray(a)?a.find(fn):null,indexOf:(a,v)=>Array.isArray(a)?a.indexOf(v):-1,join:(a,sep)=>Array.isArray(a)?a.join(sep??','):'',slice:(a,s,e)=>Array.isArray(a)?a.slice(s,e):[],reverse:(a)=>Array.isArray(a)?[...a].reverse():[],sort:(a)=>Array.isArray(a)?[...a].sort():[],unique:(a)=>Array.isArray(a)?[...new Set(a)]:[]};`);
    this.emit(``);
    // animation runtime
    this.emit(`function __buildGrid(w,h,bg){return Array.from({length:h},()=>Array(w).fill(bg));}`);
    this.emit(`function __renderGrid(grid){return grid.map(r=>r.join('')).join('\\n');}`);
    this.emit(`function __applyAction(grid,action,sprites,w,h){const cells=sprites[action.spriteName];if(!cells||action.stays)return;if(action.clear)return;if(action.fillRow!==undefined){for(let c=0;c<w;c++)if(action.fillRow>=0&&action.fillRow<h)grid[action.fillRow][c]=cells[0].emoji;return;}if(action.fillCol!==undefined){for(let r=0;r<h;r++)if(action.fillCol>=0&&action.fillCol<w)grid[r][action.fillCol]=cells[0].emoji;return;}if(action.x!==undefined&&action.y!==undefined){if(action.x>=0&&action.x<h&&action.y>=0&&action.y<w)grid[action.x][action.y]=cells[0].emoji;return;}for(const cell of cells){if(cell.fillRow!==undefined){for(let c=0;c<w;c++)if(cell.fillRow>=0&&cell.fillRow<h)grid[cell.fillRow][c]=cell.emoji;}else if(cell.fillCol!==undefined){for(let r=0;r<h;r++)if(cell.fillCol>=0&&cell.fillCol<w)grid[r][cell.fillCol]=cell.emoji;}else if(cell.row!==undefined&&cell.col!==undefined){if(cell.row>=0&&cell.row<h&&cell.col>=0&&cell.col<w)grid[cell.row][cell.col]=cell.emoji;}}}`);
    // pagination runtime
    this.emit(`async function __paginate(ctx, pages, timeoutSecs=60) {`);
    this.emit(`  if(!ctx||!pages||pages.length===0)return;`);
    this.emit(`  let page=0;`);
    this.emit(`  const total=pages.length;`);
    this.emit(`  function buildRow(p,t){`);
    this.emit(`    const prev=new ButtonBuilder().setCustomId('__pg_prev').setLabel('◀').setStyle(ButtonStyle.Secondary).setDisabled(p===0);`);
    this.emit(`    const next=new ButtonBuilder().setCustomId('__pg_next').setLabel('▶').setStyle(ButtonStyle.Secondary).setDisabled(p===t-1);`);
    this.emit(`    const info=new ButtonBuilder().setCustomId('__pg_info').setLabel(\`\${p+1}/\${t}\`).setStyle(ButtonStyle.Secondary).setDisabled(true);`);
    this.emit(`    return new ActionRowBuilder().addComponents(prev,info,next);`);
    this.emit(`  }`);
    this.emit(`  const embed=pages[0];`);
    this.emit(`  const isEmbed=typeof embed==='object'&&embed?.data;`);
    this.emit(`  const payload=isEmbed?{embeds:[embed],components:[buildRow(0,total)]}:{content:String(embed),components:[buildRow(0,total)]};`);
    this.emit(`  let msg;`);
    this.emit(`  try{`);
    this.emit(`    if(ctx._isSlash&&ctx._interaction&&!ctx._interaction.replied){await ctx._interaction.reply(payload);msg=await ctx._interaction.fetchReply();}`);
    this.emit(`    else if(ctx.channel){msg=await ctx.channel.send(payload);}`);
    this.emit(`  }catch(e){console.error('[NZS] paginate failed:',e.message);return;}`);
    this.emit(`  if(!msg)return;`);
    this.emit(`  const collector=msg.createMessageComponentCollector({time:timeoutSecs*1000});`);
    this.emit(`  collector.on('collect',async i=>{`);
    this.emit(`    if(i.customId==='__pg_prev')page=Math.max(0,page-1);`);
    this.emit(`    else if(i.customId==='__pg_next')page=Math.min(total-1,page+1);`);
    this.emit(`    else{await i.deferUpdate();return;}`);
    this.emit(`    const e=pages[page];`);
    this.emit(`    const isE=typeof e==='object'&&e?.data;`);
    this.emit(`    const p2=isE?{embeds:[e],components:[buildRow(page,total)]}:{content:String(e),components:[buildRow(page,total)]};`);
    this.emit(`    await i.update(p2);`);
    this.emit(`  });`);
    this.emit(`  collector.on('end',async()=>{`);
    this.emit(`    try{await msg.edit({components:[]});}catch(e){}`);
    this.emit(`  });`);
    this.emit(`}`);
    this.emit(``);
    this.emit(`async function __playAnimation(anim,ctx){if(!ctx)return;const delay=Math.round(1000/anim.fps);const channel=ctx.channel||ctx._interaction?.channel;if(!channel)return;const grid0=__buildGrid(anim.width,anim.height,anim.background);if(anim.keyframes[0])for(const a of anim.keyframes[0].actions)__applyAction(grid0,a,anim.sprites,anim.width,anim.height);let msg;try{if(ctx._isSlash&&ctx._interaction&&!ctx._interaction.replied){await ctx._interaction.reply({content:__renderGrid(grid0)});msg=await ctx._interaction.fetchReply();}else{msg=await channel.send(__renderGrid(grid0));}}catch(e){console.error('[NZS] Animation failed:',e.message);return;}const run=async()=>{for(let i=1;i<anim.keyframes.length;i++){await new Promise(r=>setTimeout(r,delay));const grid=__buildGrid(anim.width,anim.height,anim.background);for(const a of anim.keyframes[i].actions)__applyAction(grid,a,anim.sprites,anim.width,anim.height);try{await msg.edit(__renderGrid(grid));}catch(e){return;}}if(anim.loop)await run();};run();}`);
    this.emit(``);
  }

  // ── Vars Node ─────────────────────────────────────────────────────────
  private transpileVarsNode(node: NodeDeclaration): void {
    const varStmts = node.body.filter(s => s.type === "VarStatement") as VarStatement[];
    this.emit(`// Node: ${node.name} [vars]`);
    this.emit(`const ${node.name} = {`);
    this.indent();
    this.emit(`__key: '${node.name}',`);
    this.emit(`__defaults: {`);
    this.indent();
    for (const v of varStmts) this.emit(`${v.name}: ${this.exprRaw(v.value)},`);
    this.dedent();
    this.emit(`},`);
    this.emit(`get(userId,field){return __varsGet('${node.name}',userId,field,this.__defaults[field]);},`);
    this.emit(`set(userId,field,value){return __varsSet('${node.name}',userId,field,value);},`);
    this.emit(`mod(userId,field,delta){return __varsMod('${node.name}',userId,field,delta,this.__defaults[field]??0);},`);
    this.emit(`async onLoad(){},`);
    this.emit(`async onUnload(){},`);
    this.dedent();
    this.emit(`};`);
    this.emit(``);
  }

  // ── Node ──────────────────────────────────────────────────────────────
  private transpileNode(node: NodeDeclaration): void {
    const savedMode = this.currentMode;
    if (node.mode) this.currentMode = node.mode;

    const info = this.symbols.get(node.name);
    const kind = info?.kind ?? "node";

    // skip pure container nodes that only have nested nodes/cmds — those get handled by root
    const hasCmds = node.body.some(s => s.type === "CmdDeclaration");
    const hasEvents = node.body.some(s => s.type === "EventDeclaration");
    const hasOnlyNested = node.body.every(s =>
      s.type === "NodeDeclaration" || s.type === "ModeStatement" ||
      s.type === "AssignStatement" || s.type === "UseStatement" ||
      s.type === "CmdDeclaration" || s.type === "EventDeclaration" ||
      s.type === "DefDeclaration"
    );

    // Only emit as a JS object if it has meaningful state (embeds, buttons, etc)
    const props = node.body.filter(s => s.type === "AssignStatement") as AssignStatement[];
    const methods = node.body.filter(s => s.type === "DefDeclaration") as DefDeclaration[];
    const fields = node.body.filter(s => s.type === "FieldDeclaration") as FieldDeclaration[];
    const options = node.body.filter(s => s.type === "OptionDeclaration") as OptionDeclaration[];
    const inputFields = fields.filter(f => (f as any)._isInput);
    const embedFields = fields.filter(f => !(f as any)._isInput);

    const hasState = props.length > 0 || methods.length > 0 || fields.length > 0 || options.length > 0;
    if (!hasState && !hasCmds) {
      this.currentMode = savedMode;
      return;
    }

    this.emit(`// Node: ${node.name} [${kind}]`);
    this.emit(`const ${node.name} = (() => {`);
    this.indent();

    this.emit(`const __state = {`);
    this.indent();
    for (const p of props) this.emit(`${p.name}: ${this.exprRaw(p.value)},`);
    this.dedent();
    this.emit(`};`);
    this.emit(`const __fields = [${embedFields.map(f=>`{name:${this.exprRaw(f.name)},value:${this.exprRaw(f.value)},inline:${f.inline}}`).join(",")}];`);
    this.emit(`const __options = [${options.map(o=>`{label:${this.exprRaw(o.label)},value:${this.exprRaw(o.value)}${o.description?`,description:${this.exprRaw(o.description)}`:""}}`).join(",")}];`);
    this.emit(`const __inputs = [${inputFields.map(f=>`{label:${this.exprRaw(f.name)},placeholder:${this.exprRaw(f.value)},required:${f.inline}}`).join(",")}];`);
    this.emit(``);

    if (kind === "embed") {
      this.emit(`function build(overrides={},extraFields=[]){return __buildEmbed({...__state,...overrides},[...__fields,...extraFields]);}`);
    }
    if (kind === "button") {
      const onClick = methods.find(m => m.name === "onClick");
      this.emit(`const __customId = __state.customId || '${node.name.toLowerCase()}_btn';`);
      if (onClick) {
        this.emit(`__buttonHandlers.set(__customId, async (ctx) => {`);
        this.indent();
        this.emit(`const __vars = { ctx };`);
        for (const s of onClick.body) this.emit(this.stmt(s, "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildButton(__state.label,__state.color,__customId,null);}`);
    }
    if (kind === "modal") {
      const onSubmit = methods.find(m => m.name === "onSubmit");
      this.emit(`const __modalId = __state.customId || '${node.name.toLowerCase()}_modal';`);
      if (onSubmit) {
        this.emit(`__modalHandlers.set(__modalId, async (ctx,fields) => {`);
        this.indent();
        this.emit(`const __vars = { ctx, fields };`);
        for (const s of onSubmit.body) this.emit(this.stmt(s, "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildModal(__modalId,String(__state.title||'${node.name}'),__inputs);}`);
    }
    if (kind === "select") {
      const onSelect = methods.find(m => m.name === "onSelect");
      this.emit(`const __selectId = __state.customId || '${node.name.toLowerCase()}_select';`);
      if (onSelect) {
        this.emit(`__selectHandlers.set(__selectId, async (ctx,values) => {`);
        this.indent();
        this.emit(`const __vars = { ctx, values, selected: values[0] };`);
        for (const s of onSelect.body) this.emit(this.stmt(s, "__vars", "ctx"));
        this.dedent();
        this.emit(`});`);
      }
      this.emit(`function build(){return __buildSelect(__selectId,String(__state.placeholder||'Select'),__options,null);}`);
    }

    this.emit(`async function onLoad(){}`);
    this.emit(`async function onUnload(){}`);
    this.emit(``);

    const skipMethods = new Set(["onLoad","onUnload","onClick","onSubmit","onSelect"]);
    for (const method of methods) {
      if (skipMethods.has(method.name)) continue;
      const paramNames = method.params.map(p => p.name).join(", ");
      this.emit(`async function ${method.name}(${paramNames}) {`);
      this.indent();
      this.emit(`const __vars = {${method.params.map(p => p.name).join(", ")}};`);
      for (const s of method.body) this.emit(this.stmt(s, "__vars", "null"));
      this.dedent();
      this.emit(`}`);
      this.emit(``);
    }

    const exported = methods.filter(m => !m.isPrivate && !skipMethods.has(m.name)).map(m => m.name);
    const extras = [kind === "embed" || kind === "button" || kind === "modal" || kind === "select" ? "build" : ""].filter(Boolean);
    this.emit(`return { __state, __fields, __options, __inputs, onLoad, onUnload, ${[...extras, ...exported].join(", ")} };`);
    this.dedent();
    this.emit(`})();`);
    this.emit(``);

    this.currentMode = savedMode;
  }

  // ── Animation ─────────────────────────────────────────────────────────
  private transpileAnimation(anim: AnimationDeclaration): void {
    this.emit(`// Animation: ${anim.name}`);
    this.emit(`const ${anim.name} = {`);
    this.indent();
    this.emit(`name:'${anim.name}',width:${anim.canvasWidth},height:${anim.canvasHeight},background:'${anim.background}',fps:${anim.fps},loop:${anim.loop},`);
    this.emit(`sprites:{`);
    this.indent();
    for (const sp of anim.sprites) {
      this.emit(`${sp.name}:[`);
      this.indent();
      for (const cell of sp.cells) {
        const parts = [`emoji:'${cell.emoji}'`];
        if (cell.fillRow !== undefined) parts.push(`fillRow:${cell.fillRow}`);
        if (cell.fillCol !== undefined) parts.push(`fillCol:${cell.fillCol}`);
        if (cell.row !== undefined) parts.push(`row:${cell.row}`);
        if (cell.col !== undefined) parts.push(`col:${cell.col}`);
        this.emit(`{${parts.join(",")}},`);
      }
      this.dedent();
      this.emit(`],`);
    }
    this.dedent();
    this.emit(`},`);
    this.emit(`keyframes:[`);
    this.indent();
    for (const kf of anim.keyframes) {
      this.emit(`{index:${kf.index},actions:[`);
      this.indent();
      for (const a of kf.actions) {
        const parts = [`spriteName:'${a.spriteName}'`];
        if (a.clear) parts.push(`clear:true`);
        if (a.stays) parts.push(`stays:true`);
        if (a.fillRow !== undefined) parts.push(`fillRow:${a.fillRow}`);
        if (a.fillCol !== undefined) parts.push(`fillCol:${a.fillCol}`);
        if (a.x !== undefined) parts.push(`x:${a.x}`);
        if (a.y !== undefined) parts.push(`y:${a.y}`);
        this.emit(`{${parts.join(",")}},`);
      }
      this.dedent();
      this.emit(`]},`);
    }
    this.dedent();
    this.emit(`],`);
    this.dedent();
    this.emit(`};`);
    this.emit(``);
  }

  // ── Root ──────────────────────────────────────────────────────────────
  private transpileRoot(root: RootDeclaration): void {
    if (root.mode) { this.globalMode = root.mode; this.currentMode = root.mode; }
    this.emit(`// ── Root ────────────────────────────────────────────────`);
    this.emit(`(async () => {`);
    this.indent();

    // Collect everything from root AND from nested nodes recursively
    const allCmds: CmdDeclaration[] = [];
    const allEvents: EventDeclaration[] = [];
    const allScheduled: ScheduledTask[] = [];
    const usedNodes: string[] = [];
    const assigns: AssignStatement[] = [];

    this.collectFromBody(root.body, allCmds, allEvents, allScheduled, usedNodes, assigns);

    // token, prefix, clientId
    let token = `process.env.TOKEN`;
    let clientId = `process.env.CLIENT_ID`;
    let globalPrefixes: string[] = ["!"];
    for (const a of assigns) {
      if (a.name === "token") token = this.exprRaw(a.value);
      if (a.name === "clientId") clientId = this.exprRaw(a.value);
      if (a.name === "prefix") {
        if (a.value.type === "ArrayLiteral") globalPrefixes = (a.value as ArrayLiteral).elements.map(e => (e as Literal).value as string);
        else if (a.value.type === "Literal") globalPrefixes = [(a.value as Literal).value as string];
      }
    }

    this.emit(`const __prefixes = ${JSON.stringify(globalPrefixes)};`);
    this.emit(`const __token = ${token};`);
    this.emit(`const __clientId = ${clientId};`);
    this.emit(``);

    // onLoad for used nodes
    for (const name of usedNodes) {
      const sym = this.symbols.get(name);
      if (sym) this.emit(`if(typeof ${name}!=='undefined'&&${name}.onLoad)await ${name}.onLoad();`);
    }
    this.emit(``);

    // register slash commands
    const slashCmds = allCmds.filter(c => c.isSlash);
    for (const cmd of slashCmds) {
      this.emit(`__slashCommands.push(new SlashCommandBuilder().setName('${cmd.name.toLowerCase()}').setDescription('${cmd.name} command')${
        cmd.params.map((p: ParamDeclaration) => `.addStringOption(o=>o.setName('${p.name}').setDescription('${p.name}').setRequired(false))`).join("")
      }.toJSON());`);
    }
    this.emit(``);

    // ready event
    this.emit(`__client.once('clientReady', async (c) => {`);
    this.indent();
    this.emit(`const ctx = null; const __vars = { client: c };`);
    if (slashCmds.length > 0) {
      this.emit(`try { const rest=new REST({version:'10'}).setToken(__token); await rest.put(Routes.applicationCommands(__clientId),{body:__slashCommands}); __log('Slash commands registered.'); } catch(e) { console.error('[NZS] Slash reg failed:',e.message); }`);
    }
    for (const ev of allEvents.filter(e => e.event === "ready")) {
      for (const s of ev.body) this.emit(this.stmt(s, "__vars", "null"));
    }
    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // interaction handler
    this.emit(`__client.on('interactionCreate', async (interaction) => {`);
    this.indent();
    // slash commands
    this.emit(`if (interaction.isChatInputCommand()) {`);
    this.indent();
    this.emit(`const ctx = { user:interaction.user,channel:interaction.channel,server:interaction.guild,member:interaction.member,_isSlash:true,_interaction:interaction,args:[] };`);
    for (const cmd of slashCmds) {
      this.emit(`if (interaction.commandName === '${cmd.name.toLowerCase()}') {`);
      this.indent();
      for (const p of cmd.params) this.emit(`const ${(p as ParamDeclaration).name} = interaction.options.getString('${(p as ParamDeclaration).name}')||null;`);
      this.emitCmdBody(cmd, "ctx");
      this.dedent();
      this.emit(`}`);
    }
    this.dedent();
    this.emit(`}`);
    // buttons
    this.emit(`if (interaction.isButton()) { const handler=__buttonHandlers.get(interaction.customId); if(handler){const ctx={user:interaction.user,channel:interaction.channel,server:interaction.guild,member:interaction.member,_isSlash:true,_interaction:interaction,args:[]};try{await handler(ctx);}catch(e){console.error('[NZS] Button error:',e.message);if(!interaction.replied)await interaction.reply({content:'An error occurred.',ephemeral:true});}}}` );
    this.emit(`if (interaction.isStringSelectMenu()) { const handler=__selectHandlers.get(interaction.customId); if(handler){const ctx={user:interaction.user,channel:interaction.channel,server:interaction.guild,member:interaction.member,_isSlash:true,_interaction:interaction,args:[]};try{await handler(ctx,interaction.values);}catch(e){console.error('[NZS] Select error:',e.message);}}}`);
    this.emit(`if (interaction.isModalSubmit()) { const handler=__modalHandlers.get(interaction.customId); if(handler){const ctx={user:interaction.user,channel:interaction.channel,server:interaction.guild,member:interaction.member,_isSlash:true,_interaction:interaction,args:[]};const fields={get:(id)=>interaction.fields.getTextInputValue(id)};try{await handler(ctx,fields);}catch(e){console.error('[NZS] Modal error:',e.message);}}}`);
    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // message handler
    const prefixCmds = allCmds.filter(c => !c.isSlash);
    const messageEvents = allEvents.filter(e => e.event === "message");
    this.emit(`__client.on('messageCreate', async (message) => {`);
    this.indent();
    this.emit(`if (message.author.bot) return;`);
    this.emit(`const ctx = { user:message.author,channel:message.channel,server:message.guild,member:message.member,message,args:[],_isSlash:false,get mentioned(){return __getMentioned(message);} };`);
    this.emit(`const __vars = { message, ctx, user:message.author };`);
    for (const ev of messageEvents) {
      this.emit(`try {`); this.indent();
      for (const s of ev.body) this.emit(this.stmt(s, "__vars", "ctx"));
      this.dedent(); this.emit(`} catch(e) { console.error('[NZS] on message:',e.message); }`);
    }

    // custom prefix cmds
    const customPrefixCmds = prefixCmds.filter(c => c.cmdPrefix);
    for (const cmd of customPrefixCmds) {
      const prefixes = Array.isArray(cmd.cmdPrefix) ? cmd.cmdPrefix : [cmd.cmdPrefix as string];
      const check = prefixes.map(p => `message.content.startsWith('${p}')`).join("||");
      const pvar = `__p_${cmd.name}`;
      const avar = `__a_${cmd.name}`;
      const nvar = `__n_${cmd.name}`;
      const names = [cmd.name.toLowerCase(), ...(cmd.aliases||[]).map((a:string)=>a.toLowerCase())];
      this.emit(`if(${check}){`);
      this.indent();
      this.emit(`const ${pvar}=[${prefixes.map(p=>`'${p}'`).join(",")}].find(p=>message.content.startsWith(p));`);
      this.emit(`const ${avar}=message.content.slice(${pvar}.length).trim().split(/ +/);`);
      this.emit(`const ${nvar}=(${avar}.shift()||'').toLowerCase();`);
      this.emit(`if(${names.map(n=>`${nvar}==='${n}'`).join("||")}){`);
      this.indent();
      this.emit(`ctx.args=${avar}; ctx.prefix=${pvar};`);
      for (let i = 0; i < cmd.params.length; i++) this.emit(`const ${(cmd.params[i] as ParamDeclaration).name}=${avar}[${i}]||null;`);
      this.emitCmdBody(cmd, "ctx");
      this.dedent(); this.emit(`}`);
      this.dedent(); this.emit(`}`);
    }

    // global prefix cmds
    const globalPrefixCmds = prefixCmds.filter(c => !c.cmdPrefix);
    if (globalPrefixCmds.length > 0) {
      this.emit(`const __mp=__prefixes.find(p=>message.content.startsWith(p));`);
      this.emit(`if(__mp){`);
      this.indent();
      this.emit(`const args=message.content.slice(__mp.length).trim().split(/ +/);`);
      this.emit(`const cmdName=(args.shift()||'').toLowerCase();`);
      this.emit(`ctx.args=args; ctx.prefix=__mp;`);
      for (const cmd of globalPrefixCmds) {
        const names = [cmd.name.toLowerCase(), ...(cmd.aliases||[]).map((a:string)=>a.toLowerCase())];
        this.emit(`if(${names.map(n=>`cmdName==='${n}'`).join("||")}){`);
        this.indent();
        for (let i = 0; i < cmd.params.length; i++) this.emit(`const ${(cmd.params[i] as ParamDeclaration).name}=args[${i}]||null;`);
        this.emitCmdBody(cmd, "ctx");
        this.dedent(); this.emit(`}`);
      }
      this.dedent(); this.emit(`}`);
    }
    this.dedent();
    this.emit(`});`);
    this.emit(``);

    // other events
    const eventMap: Record<string,string> = { join:"guildMemberAdd",leave:"guildMemberRemove",reaction:"messageReactionAdd",ban:"guildBanAdd",unban:"guildBanRemove",error:"error",voiceJoin:"voiceStateUpdate",voiceLeave:"voiceStateUpdate" };
    for (const ev of allEvents.filter(e => e.event !== "message" && e.event !== "ready")) {
      const de = eventMap[ev.event] || ev.event;
      this.emit(`__client.on('${de}', async (__arg) => {`);
      this.indent();
      this.emit(`try {`); this.indent();
      this.emit(`const user=__arg.user||__arg.member?.user||__arg;`);
      this.emit(`const ctx={user,server:__arg.guild,member:__arg.member||__arg,message:__arg.message||null,_isSlash:false};`);
      this.emit(`const __vars={user,ctx};`);
      for (const s of ev.body) this.emit(this.stmt(s, "__vars", "ctx"));
      this.dedent(); this.emit(`} catch(e){ console.error('[NZS] on ${ev.event}:',e.message); }`);
      this.dedent(); this.emit(`});`);
    }

    // scheduled tasks
    for (const task of allScheduled) {
      this.emit(`setInterval(async () => {`);
      this.indent();
      this.emit(`const ctx=null; const __vars={};`);
      for (const s of task.body) this.emit(this.stmt(s, "__vars", "null"));
      this.dedent();
      this.emit(`}, __parseDuration('${task.interval}'));`);
    }

    this.emit(`await __client.login(__token);`);
    this.dedent();
    this.emit(`})();`);
  }

  // ── Collect commands/events recursively from any node ─────────────────
  private collectFromBody(
    body: ASTNode[],
    cmds: CmdDeclaration[],
    events: EventDeclaration[],
    scheduled: ScheduledTask[],
    usedNodes: string[],
    assigns: AssignStatement[]
  ): void {
    for (const s of body) {
      if (s.type === "CmdDeclaration") cmds.push(s as CmdDeclaration);
      else if (s.type === "EventDeclaration") events.push(s as EventDeclaration);
      else if (s.type === "ScheduledTask") scheduled.push(s as ScheduledTask);
      else if (s.type === "UseStatement") {
        const useName = (s as UseStatement).name;
        if (!usedNodes.includes(useName)) {
          usedNodes.push(useName);
          const sym = this.symbols.get(useName);
          if (sym?.node) this.collectFromBody(sym.node.body, cmds, events, scheduled, usedNodes, assigns);
        }
      }
      else if (s.type === "AssignStatement") assigns.push(s as AssignStatement);
      else if (s.type === "NodeDeclaration") {
        // recurse into nested nodes
        this.collectFromBody((s as NodeDeclaration).body, cmds, events, scheduled, usedNodes, assigns);
      }
    }
  }

  // ── Cmd body ──────────────────────────────────────────────────────────
  private emitCmdBody(cmd: CmdDeclaration, ctxVar: string): void {
    let accessLevel = "@everyone";
    let cooldownDuration: string | null = null;
    for (const s of cmd.body) {
      if (s.type === "AccessStatement") accessLevel = (s as AccessStatement).level;
      if (s.type === "CooldownStatement") cooldownDuration = (s as CooldownStatement).duration;
    }
    const memberExpr = cmd.isSlash ? "interaction.member" : "message.member";
    const userId = cmd.isSlash ? "interaction.user.id" : "message.author.id";

    this.emit(`if(!__checkPermission(${memberExpr},'${accessLevel}')){`);
    if (cmd.isSlash) this.emit(`  if(!interaction.replied)await interaction.reply({content:'No permission.',ephemeral:true});`);
    else this.emit(`  await message.channel.send('You do not have permission.');`);
    this.emit(`  return;`);
    this.emit(`}`);

    if (cooldownDuration) {
      this.emit(`const __cd=__checkCooldown('${cmd.name}',${userId},'${cooldownDuration}');`);
      this.emit(`if(__cd>0){`);
      const msg = "Please wait ${Math.ceil(__cd/1000)}s.";
      if (cmd.isSlash) this.emit(`  if(!interaction.replied)await interaction.reply({content:\`${msg}\`,ephemeral:true});`);
      else this.emit(`  await message.channel.send(\`${msg}\`);`);
      this.emit(`  return;`);
      this.emit(`}`);
    }

    const paramNames = cmd.params.map((p: ParamDeclaration) => p.name).join(", ");
    this.emit(`try {`);
    this.indent();
    this.emit(`const __userId = ${ctxVar}?.user?.id ?? 'global';`);
    this.emit(`const __vars = { ctx:${ctxVar}, user:${ctxVar}.user${paramNames ? ", "+paramNames : ""} };`);
    // pre-populate vars nodes
    for (const [name, sym] of this.symbols) {
      if (sym.kind === "vars") {
        this.emit(`if(typeof ${name}!=='undefined'&&${name}.__defaults){__vars['${name}']=Object.fromEntries(Object.keys(${name}.__defaults).map(k=>[k,__varsGet('${name}',__userId,k,${name}.__defaults[k])]));}`);
      }
    }
    for (const s of cmd.body) {
      if (s.type === "AccessStatement" || s.type === "CooldownStatement" || s.type === "ModeStatement") continue;
      this.emit(this.stmt(s, "__vars", ctxVar));
    }
    this.dedent();
    this.emit(`} catch(e) {`);
    this.emit(`  console.error('[NZS] cmd ${cmd.name}:',e.message);`);
    if (cmd.isSlash) this.emit(`  if(!interaction.replied)await interaction.reply({content:'An error occurred.',ephemeral:true});`);
    else this.emit(`  await message.channel.send('An error occurred.');`);
    this.emit(`}`);
  }

  // ── stmt ──────────────────────────────────────────────────────────────
  private stmt(node: ASTNode, varsName: string, ctxExpr: string): string {
    switch (node.type) {
      case "ModeStatement": return `/* mode: ${(node as ModeStatement).mode} */`;

      case "VarStatement": {
        const v = node as VarStatement;
        const val = this.expr(v.value, varsName, ctxExpr);
        let coerce = val;
        if (v.varType === "int") coerce = `Math.floor(Number(${val})||0)`;
        else if (v.varType === "float") coerce = `(Number(${val})||0)`;
        else if (v.varType === "str") coerce = `String(${val})`;
        else if (v.varType === "bool") coerce = `Boolean(${val})`;
        return `let ${v.name} = ${coerce}; ${varsName}['${v.name}'] = ${v.name};`;
      }

      case "LetStatement": {
        const l = node as LetStatement;
        return `let ${l.name} = ${this.expr(l.value, varsName, ctxExpr)}; ${varsName}['${l.name}'] = ${l.name};`;
      }

      case "AssignStatement": {
        const a = node as AssignStatement;
        const val = this.expr(a.value, varsName, ctxExpr);
        // vars.field operations
        if (a.name.includes(".")) {
          const parts = a.name.split(".");
          const nodeKey = parts[0];
          const field = parts.slice(1).join(".");
          const sym = this.symbols.get(nodeKey);
          if (sym?.kind === "vars") {
            const userId = `${ctxExpr ?? "null"}?.user?.id ?? 'global'`;
            let line = "";
            if (a.operator === "=") line = `__varsSet('${nodeKey}',${userId},'${field}',${val});`;
            else if (a.operator === "+=") line = `__varsMod('${nodeKey}',${userId},'${field}',${val},${nodeKey}.__defaults['${field}']??0);`;
            else if (a.operator === "-=") line = `__varsMod('${nodeKey}',${userId},'${field}',-(${val}),${nodeKey}.__defaults['${field}']??0);`;
            else if (a.operator === "*=") line = `__varsSet('${nodeKey}',${userId},'${field}',__varsGet('${nodeKey}',${userId},'${field}',${nodeKey}.__defaults['${field}']??0)*(${val}));`;
            else if (a.operator === "/=") line = `__varsSet('${nodeKey}',${userId},'${field}',__varsGet('${nodeKey}',${userId},'${field}',${nodeKey}.__defaults['${field}']??0)/(${val}));`;
            else line = `__varsSet('${nodeKey}',${userId},'${field}',${val});`;
            return `${line} if(!${varsName}['${nodeKey}'])${varsName}['${nodeKey}']={};${varsName}['${nodeKey}']['${field}']=__varsGet('${nodeKey}',${userId},'${field}',${nodeKey}.__defaults['${field}']);`;
          }
          // regular member assignment
          return `${a.name} ${a.operator} ${val};`;
        }
        if (a.operator === "=" && a.isDeclaration) return `let ${a.name} = ${val}; ${varsName}['${a.name}'] = ${a.name};`;
        return `${a.name} ${a.operator} ${val}; if('${a.name}' in ${varsName})${varsName}['${a.name}']=${a.name};`;
      }

      case "ReturnStatement": {
        const r = node as ReturnStatement;
        return r.value ? `return ${this.expr(r.value, varsName, ctxExpr)};` : `return;`;
      }

      case "IfStatement": {
        const i = node as IfStatement;
        let out = `if(${this.expr(i.condition, varsName, ctxExpr)}){`;
        for (const s of i.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        out += `\n}`;
        for (const ei of i.elseIfs) {
          out += ` else if(${this.expr(ei.condition, varsName, ctxExpr)}){`;
          for (const s of ei.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
          out += `\n}`;
        }
        if (i.elseBody) {
          out += ` else {`;
          for (const s of i.elseBody) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
          out += `\n}`;
        }
        return out;
      }

      case "MatchStatement": {
        const m = node as MatchStatement;
        const val = this.expr(m.value, varsName, ctxExpr);
        let out = `switch(${val}){`;
        for (const c of m.cases) {
          out += `\ncase ${this.expr(c.pattern, varsName, ctxExpr)}:`;
          for (const s of c.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
          out += `\n  break;`;
        }
        if (m.defaultBody) {
          out += `\ndefault:`;
          for (const s of m.defaultBody) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        }
        return out + `\n}`;
      }

      case "TryCatch": {
        const t = node as TryCatch;
        let out = `try{`;
        for (const s of t.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        out += `\n}catch(${t.catchVar}){`;
        for (const s of t.catchBody) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        return out + `\n}`;
      }

      case "ForInStatement": {
        const f = node as ForInStatement;
        let out = `for(const ${f.variable} of (${this.expr(f.iterable, varsName, ctxExpr)}||[])){`;
        out += `\n  ${varsName}['${f.variable}']=${f.variable};`;
        for (const s of f.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        return out + `\n}`;
      }

      case "ForRangeStatement": {
        const f = node as ForRangeStatement;
        const from = this.expr(f.from, varsName, ctxExpr);
        const to = this.expr(f.to, varsName, ctxExpr);
        let out = `for(let ${f.variable}=${from};${f.variable}<=${to};${f.variable}++){`;
        out += `\n  ${varsName}['${f.variable}']=${f.variable};`;
        for (const s of f.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        return out + `\n}`;
      }

      case "WhileStatement": {
        const w = node as WhileStatement;
        let out = `while(${this.expr(w.condition, varsName, ctxExpr)}){`;
        for (const s of w.body) out += `\n  ${this.stmt(s, varsName, ctxExpr)}`;
        return out + `\n}`;
      }

      case "BreakStatement": return `break;`;
      case "ContinueStatement": return `continue;`;
      case "WaitStatement": return `await __wait('${(node as WaitStatement).duration}');`;
      case "ReactStatement": return `await __react(${ctxExpr},${this.expr((node as ReactStatement).emoji, varsName, ctxExpr)});`;
      case "EphemeralReply": return `await __replyEphemeral(${ctxExpr},${this.expr((node as EphemeralReply).message, varsName, ctxExpr)});`;
      case "CtxReply": return `await __ctxReply(${ctxExpr},${this.expr((node as CtxReply).message, varsName, ctxExpr)});`;
      case "CooldownStatement": case "AccessStatement": return `/* handled */`;
      case "UseStatement": return `/* use ${(node as UseStatement).name} */`;
      case "PlayStatement": return `await __playAnimation(${(node as PlayStatement).animationName},${ctxExpr});`;

      case "TemplateReply": {
        const tr = node as TemplateReply;
        const overrides = tr.overrides.map(o => `${o.key}:${this.expr(o.value, varsName, ctxExpr)}`).join(",");
        const fields = tr.fields.map(f => `{name:${this.expr(f.name, varsName, ctxExpr)},value:${this.expr(f.value, varsName, ctxExpr)},inline:${f.inline}}`).join(",");
        return `await __reply(${ctxExpr},__buildEmbed({...${tr.templateName}.__state,${overrides}},[...${tr.templateName}.__fields,${fields}]));`;
      }

      case "PaginateStatement": {
        const ps = node as PaginateStatement;
        const pagesArr = ps.pages.map(p => this.expr(p, varsName, ctxExpr)).join(",");
        const timeout = ps.timeout ?? 60;
        return `await __paginate(${ctxExpr},[${pagesArr}],${timeout});`;
      }

      case "DmStatement": {
        const d = node as DmStatement;
        return `await __dm(${this.expr(d.target, varsName, ctxExpr)},${this.expr(d.message, varsName, ctxExpr)});`;
      }

      case "RoleStatement": {
        const r = node as RoleStatement;
        return `await ${r.action==="give"?"__roleGive":"__roleRemove"}(${this.expr(r.target, varsName, ctxExpr)},${this.expr(r.role, varsName, ctxExpr)});`;
      }

      case "EmitStatement": {
        const e = node as EmitStatement;
        const args = e.args.map(a => this.expr(a, varsName, ctxExpr)).join(",");
        return `if(__eventHandlers.has('${e.event}'))for(const __h of __eventHandlers.get('${e.event}'))await __h(${args});`;
      }

      case "ReplyWithButton": {
        const rwb = node as ReplyWithButton;
        const msg = this.expr(rwb.message, varsName, ctxExpr);
        if (typeof rwb.button === "string") return `await __reply(${ctxExpr},${msg},[${rwb.button}.build()]);`;
        const btn = rwb.button as ButtonDeclaration;
        const lbl = this.expr(btn.label, varsName, ctxExpr);
        let out = `__buttonHandlers.set('${btn.customId}',async(ctx)=>{const __vars={ctx};`;
        for (const s of btn.onClickBody) out += `\n  ${this.stmt(s, "__vars", "ctx")}`;
        out += `\n});`;
        out += `\nawait __reply(${ctxExpr},${msg},[__buildButton(${lbl},'${btn.color}','${btn.customId}',null)]);`;
        return out;
      }

      case "CallExpression": return `${this.call(node as CallExpression, varsName, ctxExpr)};`;

      default: return `/* unknown: ${node.type} */`;
    }
  }

  // ── expr ──────────────────────────────────────────────────────────────
  private expr(node: ASTNode, varsName: string = "__vars", ctxExpr: string = "ctx"): string {
    switch (node.type) {
      case "Literal": {
        const l = node as Literal;
        if (l.value === null) return "null";
        if (typeof l.value === "boolean") return String(l.value);
        if (typeof l.value === "number") return String(l.value);
        if (typeof l.value === "string") {
          const esc = l.value.replace(/`/g, "\\`").replace(/\$/g, "\\$");
          return `__interpolate(\`${esc}\`,${ctxExpr??'null'},${varsName}||{})`;
        }
        return "null";
      }

      case "Identifier": {
        const id = node as Identifier;
        if (id.name === "env") return "process.env";
        if (id.name === "log") return "__log";
        if (id.name === "random") return "__random";
        if (id.name === "fetch") return "__fetch";
        if (id.name === "format") return "__format";
        if (id.name === "number") return "__number";
        if (id.name === "string") return "__string";
        if (id.name === "boolean") return "__boolean";
        if (id.name === "send") return "__send";
        if (id.name === "attach") return "__attach";
        const sym = this.symbols.get(id.name);
        if (sym?.kind === "embed" || sym?.kind === "button" || sym?.kind === "modal" || sym?.kind === "select") return `${id.name}.build()`;
        return id.name;
      }

      case "MemberExpression": {
        const m = node as MemberExpression;
        const objName = m.object.type === "Identifier" ? (m.object as Identifier).name : null;
        const sym = objName ? this.symbols.get(objName) : null;
        // vars.field read
        if (sym?.kind === "vars" && objName) {
          const userId = `${ctxExpr??'null'}?.user?.id??'global'`;
          const def = `${objName}.__defaults?.['${m.property}']`;
          return `__varsGet('${objName}',${userId},'${m.property}',${def})`;
        }
        // ctx.server.name etc
        if (objName === "ctx" && m.property === "mentioned") return `__getMentioned(${ctxExpr??'null'}?.message)`;
        const strMethods = ["upper","lower","trim","includes","replace","split","startsWith","endsWith","slice","indexOf","repeat","reverse","length"];
        if (strMethods.includes(m.property)) return `__str.${m.property}`;
        const arrMethods = ["push","pop","includes","filter","map","find","indexOf","join","slice","reverse","sort","unique"];
        if (arrMethods.includes(m.property)) return `__arr.${m.property}`;
        return `${this.expr(m.object, varsName, ctxExpr)}${m.optional?"?.":"."}${m.property}`;
      }

      case "IndexExpression": {
        const ie = node as IndexExpression;
        return `${this.expr(ie.object, varsName, ctxExpr)}[${this.expr(ie.index, varsName, ctxExpr)}]`;
      }

      case "CallExpression": return this.call(node as CallExpression, varsName, ctxExpr);

      case "BinaryExpression": {
        const b = node as BinaryExpression;
        if (b.operator === "!") return `!(${this.expr(b.right, varsName, ctxExpr)})`;
        return `(${this.expr(b.left, varsName, ctxExpr)}${b.operator}${this.expr(b.right, varsName, ctxExpr)})`;
      }

      case "NullCoalesce": {
        const n = node as NullCoalesce;
        return `(${this.expr(n.left, varsName, ctxExpr)}??(${this.expr(n.right, varsName, ctxExpr)}))`;
      }

      case "TernaryExpression": {
        const t = node as TernaryExpression;
        return `(${this.expr(t.condition, varsName, ctxExpr)}?${this.expr(t.consequent, varsName, ctxExpr)}:${this.expr(t.alternate, varsName, ctxExpr)})`;
      }

      case "IsExpression": {
        const ie = node as IsExpression;
        const val = this.expr(ie.value, varsName, ctxExpr);
        const typeMap: Record<string,string> = {
          string:`typeof ${val}==='string'`, number:`typeof ${val}==='number'`,
          boolean:`typeof ${val}==='boolean'`, null:`(${val}===null||${val}===undefined)`,
          array:`Array.isArray(${val})`,
        };
        const check = typeMap[ie.checkType] ?? `typeof ${val}==='${ie.checkType}'`;
        return ie.negated ? `!(${check})` : `(${check})`;
      }

      case "ArrayLiteral": return `[${(node as ArrayLiteral).elements.map(e => this.expr(e, varsName, ctxExpr)).join(",")}]`;

      case "MapLiteral": {
        const pairs = (node as MapLiteral).pairs.map(p => {
          const key = p.key.type === "Literal" ? (p.key as Literal).value : this.expr(p.key, varsName, ctxExpr);
          return `${key}:${this.expr(p.value, varsName, ctxExpr)}`;
        }).join(",");
        return `{${pairs}}`;
      }

      case "EmbedLiteral": {
        const el = node as EmbedLiteral;
        const pairs = el.pairs.map(p => `${p.key}:${this.expr(p.value, varsName, ctxExpr)}`).join(",");
        const fields = el.fields.map(f => `{name:${this.expr(f.name, varsName, ctxExpr)},value:${this.expr(f.value, varsName, ctxExpr)},inline:${f.inline}}`).join(",");
        return `__buildEmbed({${pairs}},[${fields}])`;
      }

      default: return "undefined";
    }
  }

  private exprRaw(node: ASTNode): string {
    switch (node.type) {
      case "Literal": {
        const l = node as Literal;
        if (l.value === null) return "null";
        if (typeof l.value === "boolean") return String(l.value);
        if (typeof l.value === "number") return String(l.value);
        return `"${String(l.value).replace(/"/g,'\\"')}"`;
      }
      case "Identifier": return (node as Identifier).name === "env" ? "process.env" : (node as Identifier).name;
      case "MemberExpression": { const m = node as MemberExpression; return `${this.exprRaw(m.object)}.${m.property}`; }
      default: return this.expr(node);
    }
  }

  // ── call ──────────────────────────────────────────────────────────────
  private call(node: CallExpression, varsName: string, ctxExpr: string): string {
    const args = node.args.map(a => this.expr(a, varsName, ctxExpr)).join(",");

    if (node.callee.type === "Identifier") {
      const name = (node.callee as Identifier).name;
      if (name === "reply") { const msg = node.args[0] ? this.expr(node.args[0], varsName, ctxExpr) : '""'; return `await __reply(${ctxExpr},${msg})`; }
      if (name === "log") return `__log(${args})`;
      if (name === "random") return `__random(${args})`;
      if (name === "fetch") return `await __fetch(${args})`;
      if (name === "format") return `__format(${args})`;
      if (name === "number") return `__number(${args})`;
      if (name === "string") return `__string(${args})`;
      if (name === "boolean") return `__boolean(${args})`;
      if (name === "send") return `await __send(${args})`;
      if (name === "react") return `await __react(${ctxExpr},${args})`;
      if (name === "channelSend") return `await __channelSend(${ctxExpr}?.server,${args})`;
      if (name === "wait") return `await __wait(${args})`;
    }

    if (node.callee.type === "MemberExpression") {
      const m = node.callee as MemberExpression;
      const obj = this.expr(m.object, varsName, ctxExpr);
      const strMethods = ["upper","lower","trim","includes","replace","split","startsWith","endsWith","slice","indexOf","repeat","reverse"];
      const arrMethods = ["push","pop","includes","filter","map","find","indexOf","join","slice","reverse","sort","unique"];
      const mathMethods = ["floor","ceil","round","abs","max","min","pow","sqrt","log","sin","cos"];
      if (strMethods.includes(m.property)) return `__str.${m.property}(${obj},${args})`;
      if (arrMethods.includes(m.property)) return `__arr.${m.property}(${obj},${args})`;
      if (m.object.type === "Identifier" && (m.object as Identifier).name === "math" && mathMethods.includes(m.property)) return `__math.${m.property}(${args})`;
      if (m.property === "showModal") return `await ${ctxExpr}?._interaction?.showModal(${obj.replace(".build()","")}.build())`;
    }

    return `await ${this.expr(node.callee, varsName, ctxExpr)}(${args})`;
  }

  private emit(line: string): void { this.output.push("  ".repeat(this.indentLevel) + line); }
  private indent(): void { this.indentLevel++; }
  private dedent(): void { this.indentLevel = Math.max(0, this.indentLevel - 1); }
}
